// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templates
{
    using CodeGeneratorSolution.Models;
    using System.Linq;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class SqlStoreProcedureTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 5 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"

    // تجهيز كود اختيار الأعمدة اللغوية (CASE WHEN) لكي نستخدمه في GetList و GetDetails
    var localizedSelectLines = new List<string>();
    foreach(var col in Table.Columns)
    {
        if(col.Name.EndsWith("Ar") && Table.LocalizedColumnPrefixes.Contains(col.Name.Substring(0, col.Name.Length - 2)))
        {
            var prefix = col.Name.Substring(0, col.Name.Length - 2);
            localizedSelectLines.Add($"        CASE WHEN @LangCode = 'ar' THEN [{prefix}Ar] ELSE [{prefix}En] END AS [{prefix}]");
        }
        else if(col.Name.EndsWith("En") && Table.LocalizedColumnPrefixes.Contains(col.Name.Substring(0, col.Name.Length - 2)))
        {
            continue; // تجاهل العمود الإنجليزي لأنه دُمج في السطر السابق
        }
        else
        {
            localizedSelectLines.Add($"        [{col.Name}]");
        }
    }
    string localizedSelectQuery = string.Join(",\n", localizedSelectLines);

            
            #line default
            #line hidden
            this.Write("-- ==========================================================\r\n-- Stored Procedur" +
                    "es for Table: ");
            
            #line 27 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write(@"
-- Generated by Enterprise Architect Tool
-- Safe Segregation: ALL procedures are prefixed with usp_Base_
-- ==========================================================


-------------------------------------------------------------
-- 1. INSERT PROCEDURE (Write Pipeline)
-------------------------------------------------------------
CREATE OR ALTER PROCEDURE [dbo].[usp_Base_");
            
            #line 36 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_Insert]\r\n    ");
            
            #line 37 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(",\n    ", Table.Columns.Where(c => c.IncludeInInsert).Select(c => c.SqlParameterName + " " + c.SqlFullType))));
            
            #line default
            #line hidden
            this.Write("\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n\r\n    INSERT INTO [");
            
            #line 42 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("] (\r\n        ");
            
            #line 43 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", Table.Columns.Where(c => c.IncludeInInsert).Select(c => "[" + c.Name + "]"))));
            
            #line default
            #line hidden
            this.Write("\r\n    )\r\n    VALUES (\r\n        ");
            
            #line 46 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", Table.Columns.Where(c => c.IncludeInInsert).Select(c => c.SqlParameterName))));
            
            #line default
            #line hidden
            this.Write("\r\n    );\r\n    \r\n    -- متوافق مع Dapper: ExecuteScalarAsync\r\n    SELECT CAST(SCOP" +
                    "E_IDENTITY() AS ");
            
            #line 50 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlFullType));
            
            #line default
            #line hidden
            this.Write(");\r\nEND\r\nGO\r\n\r\n-------------------------------------------------------------\r\n-- " +
                    "2. UPDATE PROCEDURE (Write Pipeline)\r\n------------------------------------------" +
                    "-------------------\r\nCREATE OR ALTER PROCEDURE [dbo].[usp_Base_");
            
            #line 57 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_Update]\r\n    ");
            
            #line 58 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 58 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlFullType));
            
            #line default
            #line hidden
            this.Write(",\r\n    ");
            
            #line 59 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(",\n    ", Table.Columns.Where(c => c.IncludeInUpdate && !c.IsPrimaryKey).Select(c => c.SqlParameterName + " " + c.SqlFullType))));
            
            #line default
            #line hidden
            this.Write("\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n\r\n    UPDATE [");
            
            #line 64 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("]\r\n    SET \r\n        ");
            
            #line 66 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(",\n        ", Table.Columns.Where(c => c.IncludeInUpdate && !c.IsPrimaryKey).Select(c => "[" + c.Name + "] = " + c.SqlParameterName))));
            
            #line default
            #line hidden
            this.Write("\r\n    WHERE [");
            
            #line 67 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.Name));
            
            #line default
            #line hidden
            this.Write("] = ");
            
            #line 67 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(";\r\nEND\r\nGO\r\n\r\n-------------------------------------------------------------\r\n-- 3" +
                    ". DELETE PROCEDURE (Write Pipeline)\r\n-------------------------------------------" +
                    "------------------\r\nCREATE OR ALTER PROCEDURE [dbo].[usp_Base_");
            
            #line 74 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_Delete]\r\n    ");
            
            #line 75 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 75 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlFullType));
            
            #line default
            #line hidden
            this.Write("\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n\r\n    DELETE FROM [");
            
            #line 80 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("]\r\n    WHERE [");
            
            #line 81 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.Name));
            
            #line default
            #line hidden
            this.Write("] = ");
            
            #line 81 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(";\r\nEND\r\nGO\r\n\r\n-------------------------------------------------------------\r\n-- 4" +
                    ". GET ALL & GET BY ID (Raw Entity Data for Edit Screens)\r\n----------------------" +
                    "---------------------------------------\r\nCREATE OR ALTER PROCEDURE [dbo].[usp_Ba" +
                    "se_");
            
            #line 88 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_GetAll]\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n    -- نرجع كل الأعمدة بدون CASE لأن هذ" +
                    "ه الدالة تُستخدم لجلب الـ Entity الخام للتعديل\r\n    SELECT * FROM [");
            
            #line 93 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("];\r\nEND\r\nGO\r\n\r\nCREATE OR ALTER PROCEDURE [dbo].[usp_Base_");
            
            #line 97 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_GetById]\r\n    ");
            
            #line 98 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 98 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlFullType));
            
            #line default
            #line hidden
            this.Write("\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n    SELECT * FROM [");
            
            #line 102 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("]\r\n    WHERE [");
            
            #line 103 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.Name));
            
            #line default
            #line hidden
            this.Write("] = ");
            
            #line 103 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(";\r\nEND\r\nGO\r\n\r\n-------------------------------------------------------------\r\n-- 5" +
                    ". GET LIST (Read Pipeline with Localization & Pagination)\r\n---------------------" +
                    "----------------------------------------\r\nCREATE OR ALTER PROCEDURE [dbo].[usp_B" +
                    "ase_");
            
            #line 110 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_GetList]\r\n    @LangCode CHAR(2) = \'ar\',\r\n    @PageNumber INT = 1,\r\n    @PageSize" +
                    " INT = 10\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n\r\n    SELECT \r\n");
            
            #line 119 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localizedSelectQuery));
            
            #line default
            #line hidden
            this.Write("\r\n    FROM [dbo].[");
            
            #line 120 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("]\r\n");
            
            #line 121 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
 if (Table.Columns.Any(c => c.Name == "IsActive")) { 
            
            #line default
            #line hidden
            this.Write("    WHERE [IsActive] = 1\r\n");
            
            #line 123 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    ORDER BY [");
            
            #line 124 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.Name));
            
            #line default
            #line hidden
            this.Write(@"] DESC
    OFFSET (@PageNumber - 1) * @PageSize ROWS 
    FETCH NEXT @PageSize ROWS ONLY;
END
GO

-------------------------------------------------------------
-- 6. UNIQUE SELECTORS (GetDetails & Exists)
-------------------------------------------------------------
");
            
            #line 133 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
 foreach(var col in Table.Columns.Where(c => c.IsUniqueSelector)) { 
            
            #line default
            #line hidden
            this.Write("CREATE OR ALTER PROCEDURE [dbo].[usp_Base_");
            
            #line 134 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_GetDetailsBy");
            
            #line 134 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("]\r\n    ");
            
            #line 135 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 135 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.SqlFullType));
            
            #line default
            #line hidden
            this.Write(",\r\n    @LangCode CHAR(2) = \'ar\'\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n\r\n    SELECT \r\n");
            
            #line 142 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(localizedSelectQuery));
            
            #line default
            #line hidden
            this.Write("\r\n    FROM [dbo].[");
            
            #line 143 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("]\r\n    WHERE [");
            
            #line 144 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("] = ");
            
            #line 144 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(";\r\nEND\r\nGO\r\n\r\nCREATE OR ALTER PROCEDURE [dbo].[usp_Base_");
            
            #line 148 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_ExistsBy");
            
            #line 148 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("]\r\n    ");
            
            #line 149 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 149 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.SqlFullType));
            
            #line default
            #line hidden
            this.Write("\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n    \r\n    -- نعيد 1 أو 0 بطريقة سريعة جداً متوا" +
                    "فقة مع Dapper ExecuteScalar<bool>\r\n    IF EXISTS (SELECT 1 FROM [");
            
            #line 155 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("] WHERE [");
            
            #line 155 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("] = ");
            
            #line 155 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(")\r\n        SELECT 1;\r\n    ELSE\r\n        SELECT 0;\r\nEND\r\nGO\r\n");
            
            #line 161 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n-------------------------------------------------------------\r\n-- 7. EXISTS BY " +
                    "ID\r\n-------------------------------------------------------------\r\nCREATE OR ALT" +
                    "ER PROCEDURE [dbo].[usp_Base_");
            
            #line 166 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_Exists]\r\n    ");
            
            #line 167 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 167 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlFullType));
            
            #line default
            #line hidden
            this.Write("\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n\r\n    IF EXISTS (SELECT 1 FROM [");
            
            #line 172 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("] WHERE [");
            
            #line 172 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.Name));
            
            #line default
            #line hidden
            this.Write("] = ");
            
            #line 172 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(")\r\n        SELECT 1;\r\n    ELSE\r\n        SELECT 0;\r\nEND\r\nGO");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
