// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templates.Infrastructure.Mapping
{
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class DataMapperTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing System.Data;\r\nusing ");
            
            #line 6 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Entities;\r\nusing ");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\nusing ");
            
            #line 8 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Extensions; // <--- Make sure this namespace exists!\r\n\r\nnamespace" +
                    " ");
            
            #line 10 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Mapping\r\n{\r\n    public static class ");
            
            #line 12 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DataMapper\r\n    {\r\n        public static ");
            
            #line 14 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" ToEntity(this IDataReader reader)\r\n        {\r\n            return new ");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n            {\r\n");
            
            #line 18 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
 
    foreach(var col in Table.Columns) 
    { 

            
            #line default
            #line hidden
            this.Write("                // Usage: GetSafe<Type>(\"Name\")\r\n                ");
            
            #line 23 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = reader.GetSafe<");
            
            #line 23 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(">(\"");
            
            #line 23 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("\"),\r\n");
            
            #line 24 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write("            };\r\n        }\r\n\r\n\r\n        public static ");
            
            #line 31 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDTO ToListDTO(this IDataReader reader)\r\n        {\r\n            return new ");
            
            #line 33 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDTO\r\n            {\r\n");
            
            #line 35 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
 
    foreach(var col in Table.GridColumns) 
    { 

            
            #line default
            #line hidden
            this.Write("                // Usage: GetSafe<Type>(\"Name\")\r\n                ");
            
            #line 40 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = reader.GetSafe<");
            
            #line 40 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(">(\"");
            
            #line 40 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("\"),\r\n");
            
            #line 41 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write("            };\r\n        }\r\n\r\n\r\n        public static ");
            
            #line 48 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO ToDetailsDTO(this IDataReader reader)\r\n        {\r\n            return n" +
                    "ew ");
            
            #line 50 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO\r\n            {\r\n");
            
            #line 52 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
 
    foreach(var col in Table.DetailedColumns) 
    { 

            
            #line default
            #line hidden
            this.Write("                // Usage: GetSafe<Type>(\"Name\")\r\n                ");
            
            #line 57 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = reader.GetSafe<");
            
            #line 57 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(">(\"");
            
            #line 57 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("\"),\r\n");
            
            #line 58 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Mapping\DataMapperTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write("            };\r\n        }\r\n\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
