// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templates.Infrastructure.Repositories
{
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\IEntityRepositoryTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class IEntityRepositoryTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.Threading.Tasks;" +
                    "\r\nusing ");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\IEntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\nusing ");
            
            #line 8 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\IEntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Entities;\r\nusing ");
            
            #line 9 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\IEntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Interfaces; \r\n\r\nnamespace ");
            
            #line 11 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\IEntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Repositories\r\n{\r\n\r\n    // INHERITANCE: Automatically gets Add, Up" +
                    "date, Delete, GetById\r\n    public partial interface I");
            
            #line 15 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\IEntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Repository :\r\n        ICrudExtendedRepository<");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\IEntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(",");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\IEntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO, ");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\IEntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDTO,");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\IEntityRepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write("> \r\n    {\r\n        // This file is now CLEAN! \r\n        // You only add specific " +
                    "methods here later if needed.\r\n        // Example: Task<User> GetByEmailAsync(st" +
                    "ring email);\r\n        \r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
