// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templates.Infrastructure.Repositories
{
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class RepositoryTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.Data;\r\nusing Sys" +
                    "tem.Threading.Tasks;\r\nusing Microsoft.Data.SqlClient;\r\nusing Microsoft.Extension" +
                    "s.Configuration;\r\nusing Dapper; // <-- السحر يبدأ هنا\r\nusing ");
            
            #line 11 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Entities;\r\nusing ");
            
            #line 12 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\nusing ");
            
            #line 13 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Interfaces;\r\n\r\nnamespace ");
            
            #line 15 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Repositories.Generated\r\n{\r\n    public partial class ");
            
            #line 17 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("Repository : BaseRepository, I");
            
            #line 17 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(@"Repository
    {
        // =========================================================
        // 1. USP NAMES (Safe Segregation Pattern)
        // =========================================================
        // جعلناها 'virtual' لكي تستطيع تغيير اسمها في الـ Custom Partial Class
        protected virtual string GetByIdUspName => ""usp_Base_");
            
            #line 23 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_GetById\";\r\n        protected virtual string GetAllUspName => \"usp_Base_");
            
            #line 24 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_GetAll\";\r\n        protected virtual string InsertUspName => \"usp_Base_");
            
            #line 25 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_Insert\";\r\n        protected virtual string UpdateUspName => \"usp_Base_");
            
            #line 26 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_Update\";\r\n        protected virtual string DeleteUspName => \"usp_Base_");
            
            #line 27 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_Delete\";\r\n        protected virtual string GetListUspName => \"usp_Base_");
            
            #line 28 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_GetList\";\r\n        protected virtual string GetDetailsUspName => \"usp_Base_");
            
            #line 29 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_GetDetails\";\r\n        protected virtual string ExistsUspName => \"usp_Base_");
            
            #line 30 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_Exists\";\r\n\r\n        // =========================================================" +
                    "\r\n        // 2. INJECTION\r\n        // ==========================================" +
                    "===============\r\n        public ");
            
            #line 35 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(@"Repository(IConfiguration configuration) : base(configuration)
        {
        }

        // =========================================================
        // 3. STANDARD CRUD (Dapper Powered)
        // =========================================================

        public async Task<");
            
            #line 43 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("> GetByIdAsync(");
            
            #line 43 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n            using var connection = CreateConnection();\r\n        " +
                    "    // Dapper يقوم بالـ Mapping وتمرير البارامتر آلياً باستخدام الكائنات المجهول" +
                    "ة (Anonymous Objects)\r\n            return await connection.QueryFirstOrDefaultAs" +
                    "ync<");
            
            #line 47 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(">(\r\n                GetByIdUspName, \r\n                new { Id = id }, \r\n        " +
                    "        commandType: CommandType.StoredProcedure);\r\n        }\r\n\r\n        public " +
                    "async Task<IReadOnlyList<");
            
            #line 53 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(">> GetAllAsync()\r\n        {\r\n            using var connection = CreateConnection(" +
                    ");\r\n            var result = await connection.QueryAsync<");
            
            #line 56 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(">(\r\n                GetAllUspName, \r\n                commandType: CommandType.Sto" +
                    "redProcedure);\r\n            return result.AsList();\r\n        }\r\n\r\n        public" +
                    " async Task<");
            
            #line 62 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write("> AddAsync(");
            
            #line 62 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(@" entity)
        {
            using var connection = CreateConnection();
            // نمرر الـ entity بالكامل! Dapper سيفهم خصائصه ويصنع منها Parameters
            // (يجب أن ينتهي استعلام Insert الخاص بك بـ SELECT SCOPE_IDENTITY();)
            return await connection.ExecuteScalarAsync<");
            
            #line 67 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(">(\r\n                InsertUspName, \r\n                entity, \r\n                co" +
                    "mmandType: CommandType.StoredProcedure);\r\n        }\r\n\r\n        public async Task" +
                    "<bool> UpdateAsync(");
            
            #line 73 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(@" entity)
        {
            using var connection = CreateConnection();
            int rowsAffected = await connection.ExecuteAsync(
                UpdateUspName, 
                entity, 
                commandType: CommandType.StoredProcedure);
            return rowsAffected > 0;
        }

        public async Task<bool> DeleteAsync(");
            
            #line 83 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(@" id)
        {
            using var connection = CreateConnection();
            int rowsAffected = await connection.ExecuteAsync(
                DeleteUspName, 
                new { Id = id }, 
                commandType: CommandType.StoredProcedure);
            return rowsAffected > 0;
        }

        // =========================================================
        // 4. READ-MODEL DTOs & PAGINATION
        // =========================================================
        
        // تمت إضافة منطق اللغات والـ Pagination (رقم الصفحة وحجمها)
        public async Task<IReadOnlyList<");
            
            #line 98 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(@"ListDTO>> GetListAsync(string langCode, int pageNumber = 1, int pageSize = 10)
        {
            using var connection = CreateConnection();
            
            // DynamicParameters تتيح لنا إضافة البارامترات بمرونة
            var parameters = new DynamicParameters();
            parameters.Add(""@LangCode"", langCode);
            parameters.Add(""@PageNumber"", pageNumber);
            parameters.Add(""@PageSize"", pageSize);

            var result = await connection.QueryAsync<");
            
            #line 108 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("ListDTO>(\r\n                GetListUspName, \r\n                parameters, \r\n      " +
                    "          commandType: CommandType.StoredProcedure);\r\n                \r\n        " +
                    "    return result.AsList();\r\n        }\r\n\r\n");
            
            #line 116 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
 foreach(var col in Table.Columns.Where(c => c.IsUniqueSelector)) { 
            
            #line default
            #line hidden
            this.Write("        public async Task<");
            
            #line 117 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO> GetDetailsAsync(");
            
            #line 117 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 117 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CamelCaseName));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            using var connection = CreateConnection();\r\n           " +
                    " return await connection.QueryFirstOrDefaultAsync<");
            
            #line 120 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO>(\r\n                GetDetailsUspName, \r\n                new { ");
            
            #line 122 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 122 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CamelCaseName));
            
            #line default
            #line hidden
            this.Write(" }, \r\n                commandType: CommandType.StoredProcedure);\r\n        }\r\n\r\n  " +
                    "      public async Task<bool> ExistsAsync(");
            
            #line 126 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 126 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CamelCaseName));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            using var connection = CreateConnection();\r\n           " +
                    " return await connection.ExecuteScalarAsync<bool>(\r\n                ExistsUspNam" +
                    "e, \r\n                new { ");
            
            #line 131 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 131 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CamelCaseName));
            
            #line default
            #line hidden
            this.Write(" }, \r\n                commandType: CommandType.StoredProcedure);\r\n        }\r\n");
            
            #line 134 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Infrastructure\Repositories\RepositoryTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
