// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templetes.T4
{
    using System.Linq;
    using CodeGeneratorSolution.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class ctrlList : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing Sys" +
                    "tem.Threading.Tasks;\r\nusing System.Windows.Forms;\r\nusing ");
            
            #line 10 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\nusing ");
            
            #line 11 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Interfaces;\r\nusing ");
            
            #line 12 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Events;\r\nusing ");
            
            #line 13 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Interfaces;\r\n\r\nnamespace ");
            
            #line 15 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Controls\r\n{\r\n\r\n    public partial class ctrl");
            
            #line 18 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"List : UserControl, IContentList
    {

    // DECLARE THE HOOK (Notice it has no body!)
        partial void CustomizeContextMenu();



// ====================================================
        // 1. DYNAMIC FILTERING STRATEGY (T4 Generated)
        // ====================================================
        public enum FilterBy 
        { 
            None, 
");
            
            #line 32 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
 foreach(var col in Table.SearchableColumns) { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 33 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(", \r\n");
            
            #line 34 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        private FilterBy _selectedFilter = FilterBy.None;\r\n        p" +
                    "rivate List<");
            
            #line 38 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDto> _allRecords;\r\n        private readonly I");
            
            #line 39 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"Service _service;

        // CHANGED: Now a strongly-ordered List for perfect UI Binding!
        public readonly List<KeyValuePair<FilterBy, string>> FilterDisplayNames = new List<KeyValuePair<FilterBy, string>>
        {
            new KeyValuePair<FilterBy, string>(FilterBy.None, ""None""),
");
            
            #line 45 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
 foreach(var col in Table.SearchableColumns) { 
            
            #line default
            #line hidden
            this.Write("            new KeyValuePair<FilterBy, string>(FilterBy.");
            
            #line 46 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(", \"");
            
            #line 46 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.FriendlyName));
            
            #line default
            #line hidden
            this.Write("\"),\r\n");
            
            #line 47 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        };\r\n\r\n        private static readonly Dictionary<FilterBy, Func<");
            
            #line 50 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDto, string, bool>> FilterStrategies =\r\n            new Dictionary<FilterBy, " +
                    "Func<");
            
            #line 51 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDto, string, bool>>\r\n        {\r\n");
            
            #line 53 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
 foreach(var col in Table.SearchableColumns) { 
    if (col.HasAllowedValues) { 
            
            #line default
            #line hidden
            this.Write("                { FilterBy.");
            
            #line 55 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(", (dto, text) => MatchDropdwonValues(dto, text, d => d.");
            
            #line 55 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(") },\r\n");
            
            #line 56 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
  } else if (col.CSharpType == "string") { 
            
            #line default
            #line hidden
            this.Write("                { FilterBy.");
            
            #line 57 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(", (dto, text) => MatchString(dto, text, d => d.");
            
            #line 57 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(") },\r\n");
            
            #line 58 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("                { FilterBy.");
            
            #line 59 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(", (dto, text) => MatchExact(dto, text, d => d.");
            
            #line 59 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(") },\r\n");
            
            #line 60 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
  }
}

            
            #line default
            #line hidden
            this.Write("  \r\n};\r\n\r\n        // ====================================================\r\n      " +
                    "  // 2. ICONTENTLIST IMPLEMENTATION \r\n        // ===============================" +
                    "=====================\r\n        public Type EntityDtoType => typeof(");
            
            #line 68 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"ListDto);
        public event EventHandler OnAddNewRequested;
        public event EventHandler<DtoEventArgs> OnEditRequested;
        public event EventHandler<DtoEventArgs> OnDetailsRequested;

        // ====================================================
        // 3. CONSTRUCTOR & INITIALIZATION
        // ====================================================
        public ctrl");
            
            #line 76 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("List(I");
            
            #line 76 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service service)\r\n        {\r\n            InitializeComponent();\r\n            _ser" +
                    "vice = service;\r\n            _allRecords = new List<");
            
            #line 80 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"ListDto>();

            // Setup Main Filter Dropdown
            CustomizeContextMenu();
            cbFilter.DataSource = new BindingSource(FilterDisplayNames, null);
            cbFilter.DisplayMember = ""Value"";
            cbFilter.ValueMember = ""Key"";

        
    bool isHandled = false;

            // 3. THE HOOK IS SAFE HERE!
            OnConfigureHeader(this.pnlHeader, this.pbHeaderIcon, this.lblHeaderTitle, ref isHandled);
        UpdateHeaderUI(bool isHandled = false;);
            
        }

        // ====================================================
        // 1. DYNAMIC HEADER LOGIC
        // ====================================================
        private void UpdateHeaderUI(bool isHandled)
        {
            If(isHandled) return;

            if (_mode == Mode.AddNew)
            {
                lblHeaderTitle.Text = ""Add New ");
            
            #line 106 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("\";\r\n                // Uses your helper to grab the \"Add\" version of this table\'s" +
                    " icon\r\n                ResourceImageHelper.ApplyEntityIcon(pbHeaderIcon, \"");
            
            #line 108 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("\", \"add\"); \r\n            }\r\n            else\r\n            {\r\n                lblH" +
                    "eaderTitle.Text = \"Update ");
            
            #line 112 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("\";\r\n                // Uses your helper to grab the \"Edit\" version of this table\'" +
                    "s icon\r\n                ResourceImageHelper.ApplyEntityIcon(pbHeaderIcon, \"");
            
            #line 114 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@""", ""edit""); 
            }
        }

        partial void OnConfigureHeader(TableLayoutPanel headerPanel, PictureBox icon, Label title, ref bool isHandled);

        public async Task LoadDataAsync()
        {
            var result = await _service.GetListAsync();
            if (result.IsSuccess)
            {
                _allRecords = result.Data.ToList();
                RefreshDataWithFilter();
            }

            PopupMessage(result);
        }

        private void SetRecordsCountLabel() => lblRecordCount.SetRecordsCount(dgvList.Rows.Count);

        // ====================================================
        // 4. SEARCH & FILTER EXECUTION
        // ====================================================
        private List<");
            
            #line 137 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDto> GetFilteredRecords(FilterBy filterType, string searchText)\r\n        {\r\n " +
                    "           // If search text is empty (or \"All\" was selected), return everything" +
                    "\r\n            if (filterType == FilterBy.None || string.IsNullOrWhiteSpace(searc" +
                    "hText))\r\n                return _allRecords;\r\n\r\n            searchText = searchT" +
                    "ext.Replace(\"\'\", \"\'\'\"); \r\n\r\n            if (FilterStrategies.TryGetValue(filterT" +
                    "ype, out var filterFunction))\r\n                return _allRecords.Where(dto => f" +
                    "ilterFunction(dto, searchText)).ToList();\r\n\r\n            return _allRecords;\r\n  " +
                    "      }\r\n\r\n        private void RefreshDataWithFilter()\r\n        {\r\n            " +
                    "// Intelligently grab the search text from the visible control!\r\n            str" +
                    "ing searchText = txtSearch.Visible ? txtSearch.Text.Trim() : cbDropdownFilter.Se" +
                    "lectedValue?.ToString() ?? \"\";\r\n            \r\n            dgvList.DataSource = G" +
                    "etFilteredRecords(_selectedFilter, searchText);\r\n            SetRecordsCountLabe" +
                    "l();\r\n        }\r\n\r\n        private void cbFilter_SelectedIndexChanged(object sen" +
                    "der, EventArgs e)\r\n        {\r\n            if (!(cbFilter.SelectedValue is Filter" +
                    "By selected)) return;\r\n            \r\n            _selectedFilter = selected;\r\n\r\n" +
                    "            // Reset UI Visibility\r\n            txtSearch.Visible = false;\r\n    " +
                    "        cbDropdownFilter.Visible = false;\r\n\r\n            if (_selectedFilter == " +
                    "FilterBy.None) \r\n            {\r\n                RefreshDataWithFilter();\r\n      " +
                    "          return;\r\n            }\r\n\r\n           // 2. T4 Magic: Determine which c" +
                    "ontrol to show and populate it!\r\n            switch (_selectedFilter)\r\n         " +
                    "   {\r\n");
            
            #line 179 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
 
    // ==========================================================
    // BLOCK 1: BOOLEAN COLUMNS (Grouped with Fall-Through!)
    // ==========================================================
    if (Table.DropdownStandardBooleanColumns.Any()) { 
        foreach(var col in Table.DropdownStandardBooleanColumns) { 

            
            #line default
            #line hidden
            this.Write("                case FilterBy.");
            
            #line 186 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(":\r\n");
            
            #line 187 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
      } 
            
            #line default
            #line hidden
            this.Write("                    cbDropdownFilter.DataSource = GetBooleanFilterOptions();\r\n   " +
                    "                 ShowDropdownFilter();\r\n                    break;\r\n");
            
            #line 191 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
  } 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 193 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
 
    // ==========================================================
    // BLOCK 2: CUSTOM SQL ENUM COLUMNS (Generated Individually)
    // ==========================================================
    foreach(var col in Table.DropdownCustomColumns) { 

            
            #line default
            #line hidden
            this.Write("                case FilterBy.");
            
            #line 199 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(":\r\n                    cbDropdownFilter.DataSource = new List<KeyValuePair<string" +
                    ", string>>\r\n                    {\r\n                        new KeyValuePair<stri" +
                    "ng, string>(\"All\", \"\"),\r\n");
            
            #line 203 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
      foreach(var val in col.AllowedFilterValues) { 
            
            #line default
            #line hidden
            this.Write("                        new KeyValuePair<string, string>(\"");
            
            #line 204 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 204 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(val));
            
            #line default
            #line hidden
            this.Write("\"),\r\n");
            
            #line 205 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
      } 
            
            #line default
            #line hidden
            this.Write("                    };\r\n                    ShowDropdownFilter();\r\n              " +
                    "      break;\r\n");
            
            #line 209 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
  } 
            
            #line default
            #line hidden
            this.Write(@"
                default:
                    txtSearch.Visible = true;
                    txtSearch.Text = string.Empty;
                    txtSearch.Focus();
                    break;
            }
        }

        private void txtSearch_TextChanged(object sender, EventArgs e) => RefreshDataWithFilter();
        
        private void cbDropdownFilter_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (cbDropdownFilter.Visible) RefreshDataWithFilter();
        }

        private void txtSearch_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (char.IsControl(e.KeyChar)) return;

            switch (_selectedFilter)
            {
");
            
            #line 232 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
 foreach(var col in Table.SearchableColumns.Where(c => c.CSharpType == "int" || c.CSharpType == "long" || c.CSharpType == "short" || c.CSharpType == "byte")) { 
            
            #line default
            #line hidden
            this.Write("                case FilterBy.");
            
            #line 233 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(":\r\n");
            
            #line 234 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"                    e.Handled = !char.IsDigit(e.KeyChar);
                    break;
            }
        }

        // ====================================================
        // 5. EVENT TRIGGERS
        // ====================================================
        // ... (Keep your existing btnAddNew, dgvList double click, and context menu events here) ...

      // ====================================================
        // 6. UI HELPERS
        // ====================================================
        private List<KeyValuePair<string, string>> GetBooleanFilterOptions()
        {
            return new List<KeyValuePair<string, string>>
            {
                new KeyValuePair<string, string>(""All"", """"),
                new KeyValuePair<string, string>(""Yes"", ""True""),
                new KeyValuePair<string, string>(""No"", ""False"")
            };
        }

        private void ShowDropdownFilter()
        {
            cbDropdownFilter.DisplayMember = ""Key"";
            cbDropdownFilter.ValueMember = ""Value"";
            cbDropdownFilter.Visible = true;
        }

        // ====================================================
        // 7. SEARCH STRATEGY HELPERS
        // ====================================================
        private bool MatchString(");
            
            #line 268 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDto dto, string searchText, Func<");
            
            #line 268 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDto, string> valueSelector)\r\n        {\r\n            var value = valueSelector" +
                    "(dto);\r\n            return value != null && value.Contains(searchText, StringCom" +
                    "parison.OrdinalIgnoreCase);\r\n        }\r\n\r\n        private bool MatchExact(");
            
            #line 274 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDto dto, string searchText, Func<");
            
            #line 274 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDto, object> valueSelector)\r\n        {\r\n            var value = valueSelector" +
                    "(dto);\r\n            return value?.ToString() == searchText;\r\n        }\r\n\r\n      " +
                    "  private bool MatchDropdwonValues(");
            
            #line 280 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDto dto, string searchText, Func<");
            
            #line 280 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlList.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDto, object> valueSelector)\r\n        {\r\n            var value = valueSelector" +
                    "(dto);\r\n            return value?.ToString().Equals(searchText, StringComparison" +
                    ".OrdinalIgnoreCase) ?? false;\r\n        }\r\n\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
