// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templetes.T4
{
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class ctrlAddEdit : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Windows.Forms;\r\nusing System.Threading.Tasks;\r\nusing " +
                    "");
            
            #line 6 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\nusing ");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Interfaces;\r\nusing ");
            
            #line 8 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Helpers; // For FormValidationHelper\r\nusing ");
            
            #line 9 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Interfaces; // For ISaveableControl\r\n\r\n\r\nnamespace ");
            
            #line 12 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Controls\r\n{\r\n    public partial class ctrl");
            
            #line 14 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"AddEdit : UserControl, ISaveableControl
    {
    // 1. Generate the Properties
    public UserControl HeaderControl 
    { 
        get 
        {
            UserControl header = null;
            // 2. Call the partial method hook!
            OnProvideHeaderControl(ref header);
            return header;
        } 
    }

    public UserControl BottomControl 
    { 
        get 
        {
            UserControl bottom = null;
            OnProvideBottomControl(ref bottom);
            return bottom;
        } 
    }

    // 3. Define the Partial Method Signatures
    // If you don't implement these in a custom file, the C# compiler ignores them!
    partial void OnProvideHeaderControl(ref UserControl header);
    partial void OnProvideBottomControl(ref UserControl bottom);

        public enum enMode { AddNew, Update }
        
        private enMode _mode = enMode.AddNew;
        private readonly I");
            
            #line 46 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service _service;\r\n        private ");
            
            #line 47 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(@" _currentId;


        public event EventHandler OnCancelRequested;  
        public event EventHandler OnSaveRequested;  
        public event EventHandler OnSaveComplete;  

        // 1. Declare the events mandated by the interface
        public event EventHandler OnDataLoaded;
        public event EventHandler<bool> OnValidationStateChanged;
        public event EventHandler OnRequestFormClose;

        // ====================================================
        // CONSTRUCTOR (Dependency Injection)
        // ====================================================
public ctrl");
            
            #line 62 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("AddEdit(I");
            
            #line 62 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"Service service)
        {
            InitializeComponent();
            _service = service;
             // Implementation: The user types an ID and hits Enter. Boom.
        txtSearch.HandleEnterKey(() => btnSearch.PerformClick());

           bool isHandled = false;

            // 3. THE HOOK IS SAFE HERE!
            OnConfigureHeader(this.pnlHeader, this.pbHeaderIcon, this.lblHeaderTitle, ref isHandled);
        UpdateHeaderUI(bool isHandled = false;);
            
        }

        // ====================================================
        // 1. DYNAMIC HEADER LOGIC
        // ====================================================
        private void UpdateHeaderUI(bool isHandled)
        {
            If(isHandled) return;

            if (_mode == Mode.AddNew)
            {
                lblHeaderTitle.Text = ""Add New ");
            
            #line 86 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.FriendlyName));
            
            #line default
            #line hidden
            this.Write("\";\r\n                // Uses your helper to grab the \"Add\" version of this table\'s" +
                    " icon\r\n                ResourceImageHelper.ApplyEntityIcon(pbHeaderIcon, \"");
            
            #line 88 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("\", \"add\"); \r\n            }\r\n            else\r\n            {\r\n                lblH" +
                    "eaderTitle.Text = \"Update ");
            
            #line 92 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.FriendlyName));
            
            #line default
            #line hidden
            this.Write("\";\r\n                // Uses your helper to grab the \"Edit\" version of this table\'" +
                    "s icon\r\n                ResourceImageHelper.ApplyEntityIcon(pbHeaderIcon, \"");
            
            #line 94 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@""", ""edit""); 
            }
        }

        partial void OnConfigureHeader(TableLayoutPanel headerPanel, PictureBox icon, Label title, ref bool isHandled);

       // ====================================================
        // 1. LOAD DATA (Called by the Host Form)
        // ====================================================
        public async Task LoadDataAsync(");
            
            #line 103 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(@" id)
        {
            _currentId = id;
            _mode = enMode.Update; 
           UpdateHeaderUI();
            
            // 1. Fetch the Data
            var result = await _service.GetByIdAsync(id);
            
            if (result.IsSuccess && result.Data != null)
            {
            // 2. Fire the event! The Host Form will hear this and update the Window Title.
        OnDataLoaded?.Invoke(this, EventArgs.EventArgs.Empty);

                // 2. Delegate to the Mapping Method!
                FillControls(result.Data);
                
");
            
            #line 120 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
 if (Table.Columns.Any(c => c.IsSensitive)) { 
            
            #line default
            #line hidden
            this.Write("                // 3. Secure Sensitive Fields\r\n");
            
            #line 122 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
 if( Table.HasPassword) { 
            
            #line default
            #line hidden
            this.Write("                txtPassword.Visible = false; \r\n                lblPassword.Visibl" +
                    "e = false;\r\n");
            
            #line 125 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
 } 
            
            #line default
            #line hidden
            
            #line 126 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            }\r\n            else\r\n            {\r\n                OnCancelRequested" +
                    "?.Invoke(this, EventArgs.Empty);\r\n            }\r\n                PopupMessage(re" +
                    "sult);\r\n        }\r\n\r\n        // ================================================" +
                    "====\r\n        // 3. EXECUTION (Called by Host Form\'s Save Button)\r\n        // ==" +
                    "==================================================\r\n        public async Task<bo" +
                    "ol> SaveAsync()\r\n        {\r\n            if (_mode == enMode.AddNew)\r\n           " +
                    " {\r\n                // 1. Get the Data\r\n                var dto = GetCreateDto()" +
                    ";\r\n\r\n                // 2. Send to Service\r\n                var result = await _" +
                    "service.AddAsync(dto);\r\n                \r\n                // 3. Handle Result\r\n " +
                    "               if (!result.IsSuccess) \r\n                { \r\n                    " +
                    "FormValidationHelper.ShowErrors(this, errorProvider1, result.ValidationErrors); " +
                    "\r\n                    return false; \r\n                }\r\n                \r\n     " +
                    "           _currentId = result.Data;\r\n                OnSaveComplete?.Invoke(thi" +
                    "s, EventArgs.Empty);\r\n                return true;\r\n            }\r\n            e" +
                    "lse // UPDATE MODE\r\n            {\r\n                // 1. Get the Data\r\n         " +
                    "       var dto = GetUpdateDto();\r\n\r\n                // 2. Send to Service\r\n     " +
                    "           var result = await _service.UpdateAsync(dto);\r\n                \r\n    " +
                    "            // 3. Handle Result\r\n                if (!result.IsSuccess) \r\n      " +
                    "          { \r\n                    FormValidationHelper.ShowErrors(this, errorPro" +
                    "vider1, result.ValidationErrors); \r\n                    return false; \r\n        " +
                    "        }\r\n                \r\n                OnSaveComplete?.Invoke(this, EventA" +
                    "rgs.Empty);\r\n                return true;\r\n            }\r\n        }\r\n    }\r\n\r\n\r\n" +
                    "    // ====================================================\r\n        // 4. UI TO" +
                    " DTO MAPPING (Extracted for Clean Code)\r\n        // ============================" +
                    "========================\r\n        \r\n        private ");
            
            #line 185 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("CreateDto GetCreateDto()\r\n        {\r\n            return new ");
            
            #line 187 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("CreateDto \r\n            {\r\n");
            
            #line 189 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
 foreach(var col in Table.Columns.Where(c => c.IncludeInInsert)) { 
    if (col.WinControl == "CheckBox") { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 191 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 191 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ControlNameWithPrefix));
            
            #line default
            #line hidden
            this.Write(".Checked,\r\n");
            
            #line 192 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
  } else if (col.WinControl == "DateTimePicker") { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 193 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 193 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ControlNameWithPrefix));
            
            #line default
            #line hidden
            this.Write(".Value,\r\n");
            
            #line 194 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
  } else if (col.CSharpType != "string" && col.CSharpType != "bool" && col.CSharpType != "DateTime" && col.CSharpType != "byte[]") { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 195 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 195 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(".TryParse(");
            
            #line 195 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ControlNameWithPrefix));
            
            #line default
            #line hidden
            this.Write(".Text, out var v");
            
            #line 195 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(") ? v");
            
            #line 195 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" : default,\r\n");
            
            #line 196 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 197 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 197 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ControlNameWithPrefix));
            
            #line default
            #line hidden
            this.Write(".Text,\r\n");
            
            #line 198 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
  }
} 
            
            #line default
            #line hidden
            this.Write("            };\r\n        }\r\n\r\n        private ");
            
            #line 203 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("UpdateDto GetUpdateDto()\r\n        {\r\n            return new ");
            
            #line 205 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("UpdateDto \r\n            {\r\n                ");
            
            #line 207 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkName));
            
            #line default
            #line hidden
            this.Write(" = _currentId,\r\n");
            
            #line 208 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
 foreach(var col in Table.Columns.Where(c => c.IncludeInUpdate)) { 
    if (col.WinControl == "CheckBox") { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 210 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 210 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ControlNameWithPrefix));
            
            #line default
            #line hidden
            this.Write(".Checked,\r\n");
            
            #line 211 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
  } else if (col.WinControl == "DateTimePicker") { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 212 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 212 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ControlNameWithPrefix));
            
            #line default
            #line hidden
            this.Write(".Value,\r\n");
            
            #line 213 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
  } else if (col.CSharpType != "string" && col.CSharpType != "bool" && col.CSharpType != "DateTime" && col.CSharpType != "byte[]") { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 214 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 214 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(".TryParse(");
            
            #line 214 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ControlNameWithPrefix));
            
            #line default
            #line hidden
            this.Write(".Text, out var v");
            
            #line 214 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(") ? v");
            
            #line 214 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" : default,\r\n");
            
            #line 215 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 216 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 216 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ControlNameWithPrefix));
            
            #line default
            #line hidden
            this.Write(".Text,\r\n");
            
            #line 217 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
  }
} 
            
            #line default
            #line hidden
            this.Write(@"            };
        }

        // ====================================================
        // 5. DTO TO UI MAPPING (Extracted for Clean Code)
        // ====================================================
        
        private void FillControls(");
            
            #line 226 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Dto dto)\r\n        {\r\n            if (dto == null) return;\r\n\r\n");
            
            #line 230 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
 foreach(var col in Table.Columns.Where(c => c.IncludeInUpdate)) { 
    if (col.WinControl == "CheckBox") { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 232 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ControlNameWithPrefix));
            
            #line default
            #line hidden
            this.Write(".Checked = dto.");
            
            #line 232 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 233 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
  } else if (col.WinControl == "DateTimePicker") { 
            
            #line default
            #line hidden
            this.Write("            if (dto.");
            
            #line 234 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(".HasValue) \r\n            {\r\n                ");
            
            #line 236 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ControlNameWithPrefix));
            
            #line default
            #line hidden
            this.Write(".Value = dto.");
            
            #line 236 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(".Value;\r\n");
            
            #line 237 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
      if (col.IsNullable) { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 238 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ControlNameWithPrefix));
            
            #line default
            #line hidden
            this.Write(".Checked = true; // Enable the checkbox if it has a value\r\n");
            
            #line 239 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
      } 
            
            #line default
            #line hidden
            this.Write("            }\r\n");
            
            #line 241 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
      if (col.IsNullable) { 
            
            #line default
            #line hidden
            this.Write("            else \r\n            {\r\n                ");
            
            #line 244 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ControlNameWithPrefix));
            
            #line default
            #line hidden
            this.Write(".Checked = false; // Uncheck if null\r\n            }\r\n");
            
            #line 246 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
      } 
            
            #line default
            #line hidden
            
            #line 247 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 248 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.ControlNameWithPrefix));
            
            #line default
            #line hidden
            this.Write(".Text = dto.");
            
            #line 248 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("?.ToString();\r\n");
            
            #line 249 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlAddEdit.tt"
  }
} 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n\r\n\r\n\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
