// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templetes.T4
{
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class ctrlShowDetails : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 3 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
 
    var displayColumns = Table.DetailedColumns;

            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Threading.Tasks;\r\nusing System.Windows.Forms;\r\nusing " +
                    "");
            
            #line 9 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\nusing ");
            
            #line 10 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Interfaces;\r\nusing ");
            
            #line 11 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Helpers; \r\n\r\nnamespace ");
            
            #line 13 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Controls\r\n{\r\n    public partial class ctrl");
            
            #line 15 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ShowDetails : UserControl\r\n    {\r\n        private readonly I");
            
            #line 17 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service _service;\r\n        private ");
            
            #line 18 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(" _currentId;\r\n\r\n        public ctrl");
            
            #line 20 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ShowDetails(I");
            
            #line 20 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"Service service)
        {
            InitializeComponent();
            _service = service;
            
            bool isHandled = false;
            OnConfigureHeader(this.pnlHeader, this.pbHeaderIcon, this.lblHeaderTitle, ref isHandled);
            
            UpdateHeaderUI(isHandled);
        }

        // ====================================================
        // 1. DYNAMIC HEADER LOGIC (View Mode Only!)
        // ====================================================
        private void UpdateHeaderUI(bool isHandled)
        {
            if (isHandled) return;

            lblHeaderTitle.Text = """);
            
            #line 38 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.FriendlyName));
            
            #line default
            #line hidden
            this.Write(" Details\";\r\n            \r\n            // Assuming \"view\" or \"details\" is your sta" +
                    "ndard read-only icon convention\r\n            ResourceImageHelper.ApplyEntityIcon" +
                    "(pbHeaderIcon, \"");
            
            #line 41 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@""", ""view""); 
        }

        partial void OnConfigureHeader(TableLayoutPanel headerPanel, PictureBox icon, Label title, ref bool isHandled);

        // ====================================================
        // 2. LOAD DATA (From Database)
        // ====================================================
        public async Task LoadDataAsync(");
            
            #line 49 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(@" id)
        {
            var result = await _service.GetDetailsAsync(id);

            if (result != null && result.IsSuccess && result.Data != null)
            {
                // Pass to the overloaded method below!
                LoadData(result.Data);
                PopupMessage(result);
            }
            
            PopupMessage(result);
        }

        // ====================================================
        // 3. LOAD DATA (From passed DTO - Used by Selector!)
        // ====================================================
        public void LoadData(");
            
            #line 66 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDto dto)\r\n        {\r\n            if (dto == null) return;\r\n            \r\n " +
                    "           _currentId = dto.");
            
            #line 70 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkName));
            
            #line default
            #line hidden
            this.Write(";\r\n            FillControls(dto);\r\n        }\r\n\r\n        // ======================" +
                    "==============================\r\n        // 4. DTO TO UI MAPPING\r\n        // ====" +
                    "================================================\r\n        private void FillContr" +
                    "ols(");
            
            #line 77 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDto dto)\r\n        {\r\n");
            
            #line 79 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
 foreach(var col in displayColumns) { 
    if (col.CSharpType == "bool") { 
            
            #line default
            #line hidden
            this.Write("            lbl");
            
            #line 81 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Value.Text = dto.");
            
            #line 81 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" ? \"Yes\" : \"No\";\r\n");
            
            #line 82 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
  } else if (col.CSharpType == "DateTime") { 
            
            #line default
            #line hidden
            this.Write("            lbl");
            
            #line 83 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Value.Text = dto.");
            
            #line 83 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(".HasValue \r\n                ? dto.");
            
            #line 84 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(".Value.ToShortDateString() \r\n                : \"N/A\";\r\n");
            
            #line 86 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
  } else if (col.CSharpType == "decimal" || col.CSharpType == "double") { 
            
            #line default
            #line hidden
            this.Write("            lbl");
            
            #line 87 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Value.Text = dto.");
            
            #line 87 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(".ToString(\"C\");\r\n");
            
            #line 88 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("            lbl");
            
            #line 89 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Value.Text = dto.");
            
            #line 89 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("?.ToString() ?? \"N/A\";\r\n");
            
            #line 90 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetails.tt"
  }
} 
            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
