// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templetes.T4
{
    using System.Linq;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class ctrlShowDetailsDesigner : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nnamespace ");
            
            #line 5 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Controls\r\n{\r\n    partial class ctrl");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"ShowDetails
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) { components.Dispose(); }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            
");
            
            #line 21 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
 
            // 0. PREPARE THE LIST OF COLUMNS (Using your new DetailedColumns property!)
            var displayColumns = Table.DetailedColumns;
            int totalCols = displayColumns.Count;
            int halfPoint = (int)Math.Ceiling(totalCols / 2.0);

            // 1. INSTANTIATE CONTROLS
            foreach(var col in displayColumns) 
            { 

            
            #line default
            #line hidden
            this.Write("            this.lblIcon");
            
            #line 31 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = new System.Windows.Forms.Label();\r\n            this.lbl");
            
            #line 32 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Title = new System.Windows.Forms.Label();\r\n            this.lbl");
            
            #line 33 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Value = new System.Windows.Forms.Label();\r\n");
            
            #line 34 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
     
    } 

            
            #line default
            #line hidden
            this.Write("            \r\n              // ==================================================" +
                    "==\r\n            // HEADER PANEL SETUP (Row 0: Icon, Row 1: Title)\r\n            /" +
                    "/ ====================================================\r\n            this.pnlHead" +
                    "er.ColumnCount = 1;\r\n            this.pnlHeader.ColumnStyles.Add(new System.Wind" +
                    "ows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));\r\n          " +
                    "  this.pnlHeader.RowCount = 2;\r\n            this.pnlHeader.RowStyles.Add(new Sys" +
                    "tem.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 60F));\r\n     " +
                    "       this.pnlHeader.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Win" +
                    "dows.Forms.SizeType.Absolute, 40F));\r\n            this.pnlHeader.Dock = System.W" +
                    "indows.Forms.DockStyle.Top;\r\n            this.pnlHeader.Height = 100;\r\n         " +
                    "   this.pnlHeader.Margin = new System.Windows.Forms.Padding(0, 0, 0, 10);\r\n\r\n   " +
                    "         // HEADER ICON\r\n            this.pbHeaderIcon.Dock = System.Windows.For" +
                    "ms.DockStyle.Fill;\r\n            this.pbHeaderIcon.SizeMode = System.Windows.Form" +
                    "s.PictureBoxSizeMode.CenterImage;\r\n            \r\n            // HEADER LABEL\r\n  " +
                    "          this.lblHeaderTitle.Dock = System.Windows.Forms.DockStyle.Fill;\r\n     " +
                    "       this.lblHeaderTitle.TextAlign = System.Drawing.ContentAlignment.MiddleCen" +
                    "ter;\r\n            this.lblHeaderTitle.Font = new System.Drawing.Font(\"Segoe UI\"," +
                    " 16F, System.Drawing.FontStyle.Bold);\r\n            this.lblHeaderTitle.ForeColor" +
                    " = System.Drawing.Color.FromArgb(45, 45, 48);\r\n\r\n            this.pnlHeader.Cont" +
                    "rols.Add(this.pbHeaderIcon, 0, 0);\r\n            this.pnlHeader.Controls.Add(this" +
                    ".lblHeaderTitle, 0, 1);\r\n\r\n            // ======================================" +
                    "==============\r\n            // CONTENT PANEL SETUP (Where the generated textboxe" +
                    "s go)\r\n            // ====================================================\r\n    " +
                    "        this.pnlContent.Dock = System.Windows.Forms.DockStyle.Fill;\r\n           " +
                    " this.pnlContent.AutoScroll = true;\r\n\r\n            // ==========================" +
                    "==========================\r\n            // ADD CONTROLS TO MAIN USER CONTROL\r\n  " +
                    "          // ====================================================\r\n            t" +
                    "his.Controls.Add(this.pnlContent); // Fill goes first in Z-order\r\n            th" +
                    "is.Controls.Add(this.pnlHeader);  // Top goes last so it stays at the top\r\n");
            
            #line 74 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
 
            // 2. SET PROPERTIES AND 2-COLUMN AUTO-LAYOUT MATH
            int startY = 130;
            int yPos = startY; 
            int iconX = 30;      
            int titleX = 60;     
            int valueX = 220;    
            int verticalSpacing = 40;

            for (int i = 0; i < totalCols; i++) 
            { 
                var col = displayColumns[i];

                // COLUMN SPLIT LOGIC
                if (i == halfPoint)
                {
                    yPos = startY;       
                    iconX += 400;       
                    titleX += 400;       
                    valueX += 400;       
                }

            
            #line default
            #line hidden
            this.Write("            // \r\n            // ");
            
            #line 97 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" Row\r\n            // \r\n            this.lblIcon");
            
            #line 99 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(".AutoSize = true;\r\n            this.lblIcon");
            
            #line 100 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(".Font = new System.Drawing.Font(\"Segoe MDL2 Assets\", 11F, System.Drawing.FontStyl" +
                    "e.Bold);\r\n            this.lblIcon");
            
            #line 101 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(".Location = new System.Drawing.Point(");
            
            #line 101 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iconX));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 101 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(yPos));
            
            #line default
            #line hidden
            this.Write(");\r\n            this.lblIcon");
            
            #line 102 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(".Text = \"");
            
            #line 102 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.IconCode));
            
            #line default
            #line hidden
            this.Write("\";\r\n\r\n            this.lbl");
            
            #line 104 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Title.AutoSize = true;\r\n            this.lbl");
            
            #line 105 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Title.Font = new System.Drawing.Font(\"Segoe UI\", 10F, System.Drawing.FontStyle.Bo" +
                    "ld);\r\n            this.lbl");
            
            #line 106 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Title.Location = new System.Drawing.Point(");
            
            #line 106 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(titleX));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 106 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(yPos));
            
            #line default
            #line hidden
            this.Write(");\r\n            this.lbl");
            
            #line 107 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Title.Text = \"");
            
            #line 107 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.FriendlyName));
            
            #line default
            #line hidden
            this.Write(":\";\r\n\r\n            this.lbl");
            
            #line 109 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Value.AutoSize = true;\r\n            this.lbl");
            
            #line 110 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Value.Font = new System.Drawing.Font(\"Segoe UI\", 10F);\r\n            this.lbl");
            
            #line 111 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Value.Location = new System.Drawing.Point(");
            
            #line 111 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(valueX));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 111 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(yPos));
            
            #line default
            #line hidden
            this.Write(");\r\n            this.lbl");
            
            #line 112 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Value.Text = \"???\"; // Default placeholder\r\n\r\n");
            
            #line 114 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
 
                yPos += verticalSpacing;
            } 

            
            #line default
            #line hidden
            this.Write("            // \r\n            // ctrl");
            
            #line 119 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"ShowDetails Assembly
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.Font = new System.Drawing.Font(""Segoe UI"", 9F);

 ");
            
            #line 126 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
      
          
            // 3. ADD TO CONTROLS COLLECTION
            foreach(var col in displayColumns) 
            { 

            
            #line default
            #line hidden
            this.Write("            this.Controls.Add(this.lblIcon");
            
            #line 132 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n            this.Controls.Add(this.lbl");
            
            #line 133 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Title);\r\n            this.Controls.Add(this.lbl");
            
            #line 134 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Value);\r\n");
            
            #line 135 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
     
    } 
            int formHeight = startY + (halfPoint * verticalSpacing) + 40;

            
            #line default
            #line hidden
            this.Write("            this.Name = \"ctrl");
            
            #line 139 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ShowDetails\";\r\n            this.Size = new System.Drawing.Size(");
            
            #line 140 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iconX + 450));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 140 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(formHeight));
            
            #line default
            #line hidden
            this.Write("); \r\n            \r\n            ((System.ComponentModel.ISupportInitialize)(this.p" +
                    "bEntityIcon)).EndInit();\r\n            this.ResumeLayout(false);\r\n            thi" +
                    "s.PerformLayout();\r\n        }\r\n\r\n");
            
            #line 147 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
 
        // 4. DECLARE CLASS FIELDS
        foreach(var col in displayColumns) 
        { 

            
            #line default
            #line hidden
            this.Write("        private System.Windows.Forms.Label lblIcon");
            
            #line 152 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n        private System.Windows.Forms.Label lbl");
            
            #line 153 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Title;\r\n        private System.Windows.Forms.Label lbl");
            
            #line 154 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Value;\r\n");
            
            #line 155 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ctrlShowDetailsDesigner.tt"
    
    } 

            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
