// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templetes.T4
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class DependencyInjectionTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using Microsoft.Extensions.DependencyInjection;\r\nusing FluentValidation;\r\n\r\n// Im" +
                    "port your generated layers\r\nusing ");
            
            #line 6 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Interfaces;\r\nusing ");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Services;\r\nusing ");
            
            #line 8 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Repositories;\r\nusing ");
            
            #line 9 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Repositories;\r\nusing ");
            
            #line 10 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Base; // Location of your BaseValidator\r\n\r\nnamespace ");
            
            #line 12 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(@".UI
{
    public static class DependencyInjectionSetup
    {
        public static IServiceCollection AddGeneratedDependencies(this IServiceCollection services)
        {
       
 

            // 1. AUTO-REGISTER ALL FLUENT VALIDATORS
            // This magical line scans the assembly where BaseService lives, finds every single 
            // generated validator (e.g., UserDtoValidator), and registers them automatically!
            services.AddValidatorsFromAssemblyContaining<BaseService>();

            // 2. REGISTER GENERATED REPOSITORIES & SERVICES
");
            
            #line 27 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
 foreach(var table in Tables) { 
            
            #line default
            #line hidden
            this.Write("            // --- ");
            
            #line 28 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write(" ---\r\n            // Business Layer: Interface -> Concrete (Perfect)\r\n           " +
                    " services.AddScoped<I");
            
            #line 30 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("Repository, ");
            
            #line 30 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("Repository>();\r\n            services.AddScoped<I");
            
            #line 31 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service, ");
            
            #line 31 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service>();\r\n            \r\n            // UI Layer: Concrete Only (Perfect)\r\n    " +
                    "        services.AddTransient<ctrl");
            
            #line 34 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("List>();    \r\n            services.AddTransient<ctrl");
            
            #line 35 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("AddEdit>(); \r\n            services.AddTransient<ctrl");
            
            #line 36 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("ShowDetails>();    \r\n            services.AddTransient<ctrl");
            
            #line 37 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("SelectorCard>();    \r\n");
            
            #line 38 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DependencyInjectionTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            return services;\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
