// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templetes.T4
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class DTOsTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using ");
            
            #line 2 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs.Base;\r\n\r\nnamespace ");
            
            #line 4 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs\r\n{\r\n    // 1. Inherits ID from Base (standard Dto)\r\n    public class ");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO : BaseDtoWithId<");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n");
            
            #line 9 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
 
    foreach(var col in Table.StandrdDtoColumns) 
    {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 13 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 13 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 14 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n    // 2. Inherits ID from Base  (Update Dto)\r\n    public class ");
            
            #line 20 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO : BaseDtoWithId<");
            
            #line 20 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n");
            
            #line 22 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
 
    foreach(var col in Table.UpdateDtoColumns) 
    {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 26 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 26 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 27 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n\r\n    //  (Create Dto)\r\n    public class ");
            
            #line 34 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO : IBaseDto\r\n    {\r\n");
            
            #line 36 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
 
    foreach(var col in Table.CreateDtoColumns) 
    {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 40 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 40 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 41 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write("\r\n    // 1. Inherits ID from Base (Detailed Dto)\r\n    public class ");
            
            #line 46 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO : BaseDtoWithId<");
            
            #line 46 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n");
            
            #line 48 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
 
    foreach(var col in Table.DetailedColumns) 
    {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 52 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 52 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 53 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write("    }\r\n\r\n\r\n        // 1. Inherits ID from Base (List Dto)\r\n    public class ");
            
            #line 60 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDto : BaseDtoWithId<");
            
            #line 60 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n");
            
            #line 62 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
 
    foreach(var col in Table.GridColumns) 
    {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 66 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 66 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 67 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DTOsTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
