// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templetes.T4
{
    using System.Linq;
    using CodeGeneratorSolution.Models;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class DtoValidatorTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing FluentValidation;\r\nusing ");
            
            #line 6 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\nusing ");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Base;\r\n\r\nnamespace ");
            
            #line 9 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Validators\r\n{\r\n    // ==============================================" +
                    "======\r\n    // 1. CREATE DTO VALIDATOR\r\n    // =================================" +
                    "===================\r\n    parial public class ");
            
            #line 14 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("CreateDtoValidator : BaseValidator<");
            
            #line 14 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("CreateDto>\r\n    {\r\n        public ");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("CreateDtoValidator()\r\n        {\r\n");
            
            #line 18 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
 
        // Create DTO does NOT need the Primary Key
        foreach(var col in Table.CreateDtoColumns) 
        { 
            GenerateFluentRules(col); 
        } 

            
            #line default
            #line hidden
            this.Write("        }\r\n    }\r\n\r\n    // ====================================================\r\n" +
                    "    // 2. UPDATE DTO VALIDATOR\r\n    // =========================================" +
                    "===========\r\n    parial public class ");
            
            #line 31 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("UpdateDtoValidator : BaseValidator<");
            
            #line 31 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("UpdateDto>\r\n    {\r\n        public ");
            
            #line 33 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("UpdateDtoValidator()\r\n        {\r\n");
            
            #line 35 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
 

        // Add rules for the rest of the columns, but SKIP passwords (handled separately)
        foreach(var col in Table.UpdateDtoColumns) 
        { 
            GenerateFluentRules(col); 
        } 

            
            #line default
            #line hidden
            this.Write("CustomizeRules();\r\n        }\r\n        parial void CustomizeRules();\r\n    }\r\n\r\n");
            
            #line 48 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
 
    // ====================================================
    // 3. CONDITIONAL PASSWORD VALIDATOR
    // ====================================================
    // Only generate this class IF the table actually has a "Password" column!
    if (Table.HasPassword && Table.PkName != null) 
    { 

            
            #line default
            #line hidden
            this.Write("    parial public class Change");
            
            #line 56 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("PasswordDtoValidator : BaseValidator<Change");
            
            #line 56 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("PasswordDto>\r\n    {\r\n        public Change");
            
            #line 58 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("PasswordDtoValidator()\r\n        {\r\n            RuleFor(x => x.");
            
            #line 60 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.Name));
            
            #line default
            #line hidden
            this.Write(@").GreaterThan(0);
            RuleFor(x => x.OldPassword).NotEmpty().WithMessage(""Old password is required."");
            RuleFor(x => x.NewPassword).NotEmpty().MinimumLength(8).WithMessage(""New password must be at least 8 characters."");
        }
    }
");
            
            #line 65 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write("}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 70 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\DtoValidatorTemplate.tt"
 
    // ====================================================
    // T4 HELPER METHOD (Runs during generation)
    // ====================================================
    private void GenerateFluentRules(ColumnDefinition col)
    {
        // Start building the rule string
        string rules = $"            RuleFor(x => x.{col.Name})";
        bool hasRule = false;

        // 1. NULL CHECK (Don't use NotEmpty on booleans, as 'false' triggers it)
        if (!col.IsNullable && col.CSharpType != "bool")
        {
            rules += $".NotEmpty().WithMessage(\"{col.Name} is required.\")";
            hasRule = true;
        }

        // 2. STRING SPECIFIC RULES
        if (col.CSharpType == "string")
        {
            // Max Length
            if (col.MaxLength > 0 && col.MaxLength < 8000)
            {
                rules += $".MaximumLength({col.MaxLength}).WithMessage(\"{col.Name} cannot exceed {col.MaxLength} characters.\")";
                hasRule = true;
            }

            // Email Heuristic
            if (col.Name.EndsWith("Email") || col.Name == "EmailAddress")
            {
                rules += $".EmailAddress().WithMessage(\"A valid email format is required.\")";
                hasRule = true;
            }

            // Phone Heuristic (Simple Regex)
            if (col.Name.Contains("Phone"))
            {
                rules += $".Matches(@\"^\\+?[1-9]\\d{{1,14}}$\").WithMessage(\"Invalid phone number format.\")";
                hasRule = true;
            }

            // Password Heuristic
            if (col.Name.Contains("Password"))
            {
                rules += $".MinimumLength(8).WithMessage(\"Password must be at least 8 characters.\")";
                hasRule = true;
            }
        }

        // 3. NUMERIC/FOREIGN KEY HEURISTIC
        if ((col.CSharpType == "int" || col.CSharpType == "long") && col.Name.EndsWith("Id"))
        {
            rules += $".GreaterThan(0).WithMessage(\"A valid {col.Name} must be selected.\")";
            hasRule = true;
        }

        // If we found at least one rule to apply, write it to the file!
        if (hasRule)
        {
            WriteLine(rules + ";");
        }
    }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
