// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templetes.T4
{
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class IEntityServiceTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.Threading.Tasks;" +
                    "\r\nusing ");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\nusing ");
            
            #line 8 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Entities.Base; \r\nusing CodeGeneratorSolution.Templetes.Infrastructure.Utili" +
                    "ties; // For Result<T>\r\n\r\nnamespace ");
            
            #line 11 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Interfaces\r\n{\r\n\r\n    // ============================================" +
                    "========\r\n    //  SERVICE INTERFACE\r\n    // ====================================" +
                    "================\r\n    public interface I");
            
            #line 17 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service : IService<");
            
            #line 17 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 17 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        Task<Result<IEnumerable<");
            
            #line 19 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Dto>>> GetAllAsync();\r\n        Task<Result<");
            
            #line 20 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Dto>> GetByIdAsync(");
            
            #line 20 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(" id);\r\n        Task<Result<");
            
            #line 21 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(">> AddAsync(");
            
            #line 21 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("CreateDto dto);\r\n        Task<Result<bool>> UpdateAsync(");
            
            #line 22 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("UpdateDto dto);\r\n        Task<Result<bool>> DeleteAsync(");
            
            #line 23 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(" id);\r\n\r\n");
            
            #line 25 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
 
        // Use .Any() so we only generate this method ONCE, 
        // even if there are multiple sensitive columns.
        if (Table.HasPassword) 
        { 

            
            #line default
            #line hidden
            this.Write("        Task<Result<bool>> ChangePasswordAsync(");
            
            #line 31 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ChangePasswordDto dto);\r\n");
            
            #line 32 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\IEntityServiceTemplate.tt"
 
        } 

            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
