// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templetes.T4
{
    using System.Collections.Generic;
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class MappingExtensionTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing ");
            
            #line 6 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Entities;\r\nusing ");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\n\r\nnamespace ");
            
            #line 9 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Mapping\r\n{\r\n    public static partial class ");
            
            #line 11 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("MappingExtensions\r\n    {\r\n        // ==========================================\r\n" +
                    "        // 1. TO DTO (Entity -> DTO)\r\n        // ===============================" +
                    "===========\r\n        public static ");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO ToDto(this ");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity)\r\n        {\r\n            if (entity == null) return null;\r\n\r\n            " +
                    "var dto = new ");
            
            #line 20 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO();\r\n\r\n");
            
            #line 22 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
 
    foreach(var col in Table.Columns) 
    {
        // 1. SKIP Sensitive Fields
        if (col.IsSensitive) continue;

        // 2. GENERATE Mapping

            
            #line default
            #line hidden
            this.Write("            dto.");
            
            #line 30 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = entity.");
            
            #line 30 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 31 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write(@"
            // Hook: Custom logic (e.g. formatting dates, computing FullName)
            OnToDto(entity, dto);

            return dto;
        }

        // ==========================================
        // 2. TO ENTITY (DTO -> Entity)
        // ==========================================
        public static ");
            
            #line 44 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" ToEntity(this ");
            
            #line 44 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO dto)\r\n        {\r\n            if (dto == null) return null;\r\n\r\n            var" +
                    " entity = new ");
            
            #line 48 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("();\r\n\r\n");
            
            #line 50 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
 
    foreach(var col in Table.Columns) 
    {
         // 1. SKIP Sensitive Fields
        if (col.IsSensitive) continue;

        // 3. GENERATE Mapping

            
            #line default
            #line hidden
            this.Write("            entity.");
            
            #line 58 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = dto.");
            
            #line 58 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 59 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write(@"
            // Hook: Custom logic (e.g. Hashing Password)
            OnToEntity(dto, entity);

            return entity;
        }

        // ==========================================
        // CREATE: UI -> Entity
        // ==========================================
        public static ");
            
            #line 72 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" ToEntity(this ");
            
            #line 72 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("CreateDto dto)\r\n        {\r\n            if (dto == null) return null;\r\n           " +
                    " return new ");
            
            #line 75 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n            {\r\n");
            
            #line 77 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
 foreach(var col in Table.Columns.Where(c => c.IncludeInInsert)) { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 78 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = dto.");
            
            #line 78 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 79 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            };\r\n        }\r\n\r\n        // =========================================" +
                    "=\r\n        // UPDATE: UI -> Existing Entity\r\n        // ========================" +
                    "==================\r\n        public static void ApplyToEntity(this ");
            
            #line 86 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("UpdateDto dto, ");
            
            #line 86 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity)\r\n        {\r\n            if (dto == null || entity == null) return;\r\n    " +
                    "        \r\n");
            
            #line 90 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
 foreach(var col in Table.Columns.Where(c => c.IncludeInUpdate)) { 
            
            #line default
            #line hidden
            this.Write("            entity.");
            
            #line 91 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = dto.");
            
            #line 91 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 92 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"        // ==========================================
        // 3. PARTIAL METHODS (The Hooks)
        // ==========================================
        // Implement these in a separate file (e.g. UserMappingExtensions.Custom.cs)
        static partial void OnToDto(");
            
            #line 97 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity, ");
            
            #line 97 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO dto);\r\n        static partial void OnToEntity(");
            
            #line 98 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO dto, ");
            
            #line 98 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity);\r\n        static partial void OnToDto(");
            
            #line 99 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity, ");
            
            #line 99 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("CreateDto dto);\r\n        static partial void OnToEntity(");
            
            #line 100 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("CreateDto dto, ");
            
            #line 100 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity);\r\n        static partial void OnToDto(");
            
            #line 101 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity, ");
            
            #line 101 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("UpdateDto dto);\r\n        static partial void OnToEntity(");
            
            #line 102 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("UpdateDto dto, ");
            
            #line 102 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity);\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
