// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templetes.T4
{
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\RepositoryInterfaceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class RepositoryInterfaceTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing System.Collections.Generic;\r\nusing System.Threading.Tasks;" +
                    "\r\nusing ");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Entities;\r\nusing ");
            
            #line 8 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Repositories.Base; // Import Base\r\n\r\nnamespace ");
            
            #line 10 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Repositories\r\n{\r\n");
            
            #line 12 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\RepositoryInterfaceTemplate.tt"
 
    // Identify Primary Key Type (Default to int)
    
    

            
            #line default
            #line hidden
            this.Write("    // INHERITANCE: Automatically gets Add, Update, Delete, GetById\r\n    public i" +
                    "nterface I");
            
            #line 18 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Repository : IRepository<");
            
            #line 18 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 18 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\RepositoryInterfaceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        // This file is now CLEAN! \r\n        // You only add specific m" +
                    "ethods here later if needed.\r\n        // Example: Task<User> GetByEmailAsync(str" +
                    "ing email);\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
