// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templetes.T4
{
    using System.Linq;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class ServiceTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing Syste" +
                    "m.Threading.Tasks;\r\nusing FluentValidation;\r\nusing ");
            
            #line 9 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\nusing ");
            
            #line 10 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Interfaces;\r\nusing ");
            
            #line 11 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Interfaces;\r\nusing CodeGeneratorSolution.Templetes.Infrastructure" +
                    "; // For ServiceExecutor\r\nusing CodeGeneratorSolution.Templetes.Infrastructure.U" +
                    "tilities; // For Result<T>\r\n\r\nnamespace ");
            
            #line 15 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Services\r\n{\r\n\r\n   public class ");
            
            #line 18 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service : BaseService, I");
            
            #line 18 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service\r\n    {\r\n        private readonly I");
            
            #line 20 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Repository _repository;\r\n\r\n        // Dependency Injection now demands the Repo a" +
                    "nd the global Waiter (ServiceProvider)\r\n        public ");
            
            #line 23 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service(\r\n            I");
            
            #line 24 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Repository repository, \r\n            IServiceProvider serviceProvider) : base(ser" +
                    "viceProvider)\r\n        {\r\n            _repository = repository;\r\n        }\r\n\r\n  " +
                    "      public async Task<Result<IEnumerable<");
            
            #line 30 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Dto>>> GetAllAsync()\r\n        {\r\n            return await ServiceExecutor.RunAsyn" +
                    "c(async () =>\r\n            {\r\n                var data = await _repository.GetAl" +
                    "lAsync();\r\n                return Result<IEnumerable<");
            
            #line 35 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Dto>>.Success(data.ForEach(r => r.ToDto).ToList());\r\n            });\r\n        }\r\n" +
                    "\r\n        public async Task<Result<IEnumerable<");
            
            #line 39 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDto>>> GetListAsync()\r\n        {\r\n            return await ServiceExecutor.Ru" +
                    "nAsync(async () =>\r\n            {\r\n                var data = await _repository." +
                    "GetListAsync();\r\n                return Result<IEnumerable<");
            
            #line 44 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDto>>.Success(data);\r\n            });\r\n        }\r\n\r\n        public async Task" +
                    "<Result<");
            
            #line 48 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"Dto>> GetByIdAsync(Table.PkType id)
        {
            return await ServiceExecutor.RunAsync(async () =>
            {
                var data = await _repository.GetByIdAsync(id);
                
                if (data == null)
                    return Result<");
            
            #line 55 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Dto>.Failure(\"");
            
            #line 55 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" not found.\");\r\n\r\n                return Result<");
            
            #line 57 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Dto>.Success(data.ToDto);\r\n            });\r\n        }\r\n        public async Task<" +
                    "Result<");
            
            #line 60 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"DetailsDTO>> GetDetailedByIdAsync(Table.PkType id)
        {
            return await ServiceExecutor.RunAsync(async () =>
            {
                var data = await _repository.GetDetailedByIdAsync(id);
                
                if (data == null)
                    return Result<");
            
            #line 67 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Dto>.Failure(\"");
            
            #line 67 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" not found.\");\r\n\r\n                return Result<");
            
            #line 69 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Dto>.Success(data);\r\n            });\r\n        }\r\n\r\n        public async Task<Resu" +
                    "lt<Table.PkType>> AddAsync(");
            
            #line 73 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"CreateDto dto)
        {
            return await ServiceExecutor.RunAsync(async () =>
            {
                // --- 1. FluentValidation Execution using the BaseService Helper ---
                var validationResult = await ValidateDtoAsync(dto);
                
                if (!validationResult.IsSuccess)
                {
                    // Fails gracefully returning the FluentValidation error string
                    return Result<bool>.Failure(validationResult.ErrorMessage);
                }

                // --- 2. Database Operation ---
                Table.PkType NewId;

                NewId = await _repository.AddAsync(dto.ToEntity()); // Ensure your AddAsync returns int/TKey

                return Result<bool>.Success(NewId);
            });

        public async Task<Result<bool>> UpdateAsync(");
            
            #line 94 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\ServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"UpdateDto dto)
        {
            return await ServiceExecutor.RunAsync(async () =>
            {
                // --- 1. FluentValidation Execution using the BaseService Helper ---
                var validationResult = await ValidateDtoAsync(dto);
                
                if (!validationResult.IsSuccess)
                {
                    // Fails gracefully returning the FluentValidation error string
                    return Result<bool>.Failure(validationResult.ErrorMessage);
                }

                // --- 2. Database Operation ---
                bool success;

                success = await _repository.UpdateAsync(dto.ToEntity());

                return Result<bool>.Success(success);
            });
        }

        public async Task<Result<bool>> DeleteAsync(int id)
        {
            return await ServiceExecutor.RunActionAsync(async () =>
            {
                await _repository.DeleteAsync(id);
            });
        }
    }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
