// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templetes.T4
{
    using CodeGeneratorSolution.Models;
    using System.Linq;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class SqlStoreProcedureTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n-- ==========================================================\r\n-- Stored Proced" +
                    "ures for Table: ");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write(@"
-- Generated by Enterprise Architect Tool
-- Pattern: Clean Property Usage (SqlFullType, SqlParameterName)
-- ==========================================================


-------------------------------------------------------------
-- 1. INSERT PROCEDURE
-------------------------------------------------------------
CREATE OR ALTER PROCEDURE [dbo].[usp_");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_Insert]\r\n    ");
            
            #line 17 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(",\n    ", Table.Columns.Where(c => c.IncludeInInsert).Select(c => c.SqlParameterName + " " + c.SqlFullType))));
            
            #line default
            #line hidden
            this.Write(",\r\n    @NewID INT OUTPUT\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n\r\n    INSERT INTO [");
            
            #line 23 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("] (\r\n        ");
            
            #line 24 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", Table.Columns.Where(c => c.IncludeInInsert).Select(c => "[" + c.Name + "]"))));
            
            #line default
            #line hidden
            this.Write("\r\n    )\r\n    VALUES (\r\n        ");
            
            #line 27 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", Table.Columns.Where(c => c.IncludeInInsert).Select(c => c.SqlParameterName))));
            
            #line default
            #line hidden
            this.Write(@"
    );
    
    -- Return the new Identity
    SET @NewID = SCOPE_IDENTITY();
END
GO

-------------------------------------------------------------
-- 2. UPDATE PROCEDURE
-------------------------------------------------------------
CREATE OR ALTER PROCEDURE [dbo].[usp_");
            
            #line 38 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_Update]\r\n    ");
            
            #line 39 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 39 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlFullType));
            
            #line default
            #line hidden
            this.Write(",\r\n    ");
            
            #line 40 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(",\n    ", Table.Columns.Where(c => c.IncludeInUpdate).Select(c => c.SqlParameterName + " " + c.SqlFullType))));
            
            #line default
            #line hidden
            this.Write("\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n\r\n    UPDATE [");
            
            #line 45 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("]\r\n    SET \r\n        ");
            
            #line 47 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(",\n        ", Table.Columns.Where(c => c.IncludeInUpdate).Select(c => "[" + c.Name + "] = " + c.SqlParameterName))));
            
            #line default
            #line hidden
            this.Write("\r\n    WHERE [");
            
            #line 48 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.Name));
            
            #line default
            #line hidden
            this.Write("] = ");
            
            #line 48 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(@";

    -- Return 1 if updated, 0 if not found
    RETURN @@ROWCOUNT;
END
GO

-------------------------------------------------------------
-- 3. DELETE PROCEDURE
-------------------------------------------------------------
CREATE OR ALTER PROCEDURE [dbo].[usp_");
            
            #line 58 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_Delete]\r\n    ");
            
            #line 59 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 59 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlFullType));
            
            #line default
            #line hidden
            this.Write("\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n\r\n    DELETE FROM [");
            
            #line 64 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("]\r\n    WHERE [");
            
            #line 65 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.Name));
            
            #line default
            #line hidden
            this.Write("] = ");
            
            #line 65 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n    RETURN @@ROWCOUNT;\r\nEND\r\nGO\r\n\r\n-----------------------------------------" +
                    "--------------------\r\n-- 4. GET ALL PROCEDURE\r\n---------------------------------" +
                    "----------------------------\r\nCREATE OR ALTER PROCEDURE [dbo].[usp_");
            
            #line 74 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_GetAll]\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n\r\n    SELECT * FROM [");
            
            #line 79 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("];\r\nEND\r\nGO\r\n\r\n-------------------------------------------------------------\r\n-- " +
                    "5. GET BY ID PROCEDURE\r\n--------------------------------------------------------" +
                    "-----\r\n\r\n\r\n");
            
            #line 88 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
 foreach(var col in Table.Columns.Where(c => c.IsUniqueSelector)) { 
            
            #line default
            #line hidden
            this.Write("       CREATE OR ALTER PROCEDURE [dbo].[usp_");
            
            #line 89 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_GetById]\r\n    ");
            
            #line 90 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 90 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlFullType));
            
            #line default
            #line hidden
            this.Write("\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n\r\n    SELECT * FROM [");
            
            #line 95 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("]\r\n    WHERE [");
            
            #line 96 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.Name));
            
            #line default
            #line hidden
            this.Write("] = ");
            
            #line 96 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(";\r\nEND\r\nGO\r\n");
            
            #line 99 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("-------------------------------------------------------------\r\n-- 6. EXISTS PROCE" +
                    "DURE\r\n-------------------------------------------------------------\r\nCREATE OR A" +
                    "LTER PROCEDURE [dbo].[usp_");
            
            #line 103 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("_ExistsByID]\r\n    ");
            
            #line 104 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 104 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlFullType));
            
            #line default
            #line hidden
            this.Write("\r\nAS\r\nBEGIN\r\n    SET NOCOUNT ON;\r\n\r\n    DECLARE @Res BIT;\r\n    \r\n    SELECT TOP 1" +
                    " @Res = 1 \r\n    FROM [");
            
            #line 112 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.Name));
            
            #line default
            #line hidden
            this.Write("]\r\n    WHERE [");
            
            #line 113 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.Name));
            
            #line default
            #line hidden
            this.Write("] = ");
            
            #line 113 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\SqlStoreProcedureTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PrimaryKey.SqlParameterName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n    SELECT ISNULL(@Res, 0);\r\nEND\r\nGO");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
