// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templetes.T4
{
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class WindowsFormsNavigationServiceTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Windows.Forms;\r\nusing System.Threading.Tasks;\r\nusing " +
                    "Microsoft.Extensions.DependencyInjection; // Required for GetRequiredService\r\nus" +
                    "ing ");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\nusing ");
            
            #line 8 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Controls;\r\nusing ");
            
            #line 9 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.GenericForms;\r\nusing ");
            
            #line 10 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Interfaces;\r\nusing ");
            
            #line 11 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Helpers;\r\n\r\nnamespace ");
            
            #line 13 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(@".UI
{
    public static class WindowsFormsNavigationService
    {

    private readonly IServiceProvider _serviceProvider;
    
    // 1. The O(1) Lookup Table
    private readonly Dictionary<Type, Type> _addRouteMap;

    public WindowsFormsNavigationService(IServiceProvider serviceProvider) 
    {
        _serviceProvider = serviceProvider;
        
        // 2. The T4 Template writes the Map!
        _addRouteMap = new Dictionary<Type, Type>
        {
");
            
            #line 30 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
 foreach(var table in Tables) { 
            
            #line default
            #line hidden
            this.Write("            { typeof(");
            
            #line 31 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDto), typeof(ctrl");
            
            #line 31 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("AddEdit) },\r\n");
            
            #line 32 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"        };
    }
        // ====================================================
        // 1. DYNAMIC ROUTING FOR SHOW DETAILS (Read-Only)
        // ====================================================
        public static async Task ShowDetailsAsync(IBaseDto dto)
        {
            IPopupBase content = null;

            // 1. Create a temporary scope (The Mini-Container)
using (var scope = _serviceProvider.CreateScope())
{
    // Dynamically generated Routing Table
            switch (dto)
            {
");
            
            #line 48 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
 
    // Loop through every table in your database schema
    foreach (var table in Tables) 
    { 
        string varName = table.CamelCaseName; 

            
            #line default
            #line hidden
            this.Write("                case ");
            
            #line 54 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO ");
            
            #line 54 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varName));
            
            #line default
            #line hidden
            this.Write(":\r\n                    // Utilizing Dependency Injection instead of \'new\' keyword" +
                    "!\r\n                    var ctrl");
            
            #line 56 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write(" = scope.ServiceProvider.GetRequiredService<ctrl");
            
            #line 56 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("Card>();\r\n                    await ctrl");
            
            #line 57 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write(".LoadDataAsync(");
            
            #line 57 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varName));
            
            #line default
            #line hidden
            this.Write(".Id);\r\n                    content = ctrl");
            
            #line 58 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write(";\r\n                    break;\r\n\r\n");
            
            #line 61 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write(@"                default:
                    MessageServiceHelper.ShowError($""No details view configured for {dto.GetType().Name}."", ""Routing Error"");
                    return;
            }

            if (content != null)
            {
                using (var frm = new frmGenericPopup(content))
                {
                    frm.ShowDialog();
                }
            }
}
           
        }

        // ====================================================
        // 2. DYNAMIC ROUTING FOR UPDATES (From DataGridView)
        // ====================================================
        public static void OpenAddEdit(IBaseDto gridDto = null)
        {
            UserControl content = null;

            // Failsafe for nulls
            if (gridDto == null) return; 

                  // 1. Create a temporary scope (The Mini-Container)
using (var scope = _serviceProvider.CreateScope())
{
// UPDATE MODE: Route based on the DTO type passed from the Grid
            switch (gridDto)
            {
");
            
            #line 96 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
 foreach(var table in Tables) {
 string varName = table.CamelCaseName; 

            
            #line default
            #line hidden
            this.Write("                case ");
            
            #line 99 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDto ");
            
            #line 99 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varName));
            
            #line default
            #line hidden
            this.Write(":\r\n                    var ctrl");
            
            #line 100 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write(" = scope.ServiceProvider.GetRequiredService<ctrl");
            
            #line 100 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("AddEdit>();\r\n                    \r\n                    // Pass the ID to the cont" +
                    "rol so it can fetch fresh data from the DB\r\n                    ctrl");
            
            #line 103 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write(".LoadDataAsync(");
            
            #line 103 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varName));
            
            #line default
            #line hidden
            this.Write(".Id); \r\n                    content = ctrl");
            
            #line 104 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write(";\r\n                    break;\r\n\r\n");
            
            #line 107 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templetes\T4\WindowsFormsNavigationServiceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"            }

            if (content != null)
            {
                // Drop the control into the generic wrapper and show it
                using (var frm = new frmGenericAddEdit((ISaveableControl)content))
                {
                    frm.ShowDialog();
                }
            }

   
        }
        
        // ====================================================
        // 3. GENERIC ADD NEW RECORD (No Code Duplication!)
        // ====================================================

        public void OpenAddNew(Type dtoType)
{
    // 1. O(1) Hash Lookup - Instantaneous!
    if (_addRouteMap.TryGetValue(dtoType, out Type editorType))
    {

        using (var scope = _serviceProvider.CreateScope())
        {
        // 2. Pass the resolved Type to the DI Container!
        var content = (ISaveableControl)scope.ServiceProvider.GetRequiredService(editorType);
            
            using (var frm = new frmGenericAddEdit(content)) 
            { 
                frm.ShowDialog(); 
            }
        }
    }
    else
    {
        MessageServiceHelper.ShowError($""Routing failed: No editor mapped for {dtoType.Name}"");
    }
}
    }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
