// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templates.UI.DependencyInjection
{
    using System.Linq;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class DependencyInjectionTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing Microsoft.Extensions.DependencyInjection;\r\nusing FluentVal" +
                    "idation;\r\nusing FluentValidation.DependencyInjectionExtensions;\r\n\r\n// Import you" +
                    "r generated layers\r\nusing ");
            
            #line 11 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Interfaces;\r\nusing ");
            
            #line 12 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Services;\r\nusing ");
            
            #line 13 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Repositories;\r\nusing ");
            
            #line 14 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Base; // Location of your BaseValidator\r\nusing School.UI.Controls;\r\n" +
                    "\r\nnamespace ");
            
            #line 17 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(@".UI
{
    public static class DependencyInjectionSetup
    {
        public static IServiceCollection AddGeneratedDependencies(this IServiceCollection services)
        {
       
 

            // 1. AUTO-REGISTER ALL FLUENT VALIDATORS
            // This magical line scans the assembly where BaseService lives, finds every single 
            // generated validator (e.g., UserDtoValidator), and registers them automatically!
            services.AddValidatorsFromAssemblyContaining<BaseService>();

            // 2. REGISTER GENERATED REPOSITORIES & SERVICES
");
            
            #line 32 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
 foreach(var table in Tables) { 
            
            #line default
            #line hidden
            this.Write("            // --- ");
            
            #line 33 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write(" ---\r\n            // Business Layer: Interface -> Concrete (Perfect)\r\n           " +
                    " services.AddScoped<I");
            
            #line 35 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("Repository, ");
            
            #line 35 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("Repository>();\r\n            services.AddScoped<I");
            
            #line 36 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service, ");
            
            #line 36 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service>();\r\n            \r\n            // UI Layer: Concrete Only (Perfect)\r\n    " +
                    "        services.AddTransient<ctrl");
            
            #line 39 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("List>();    \r\n            services.AddTransient<ctrl");
            
            #line 40 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("AddEdit>(); \r\n            services.AddTransient<ctrl");
            
            #line 41 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("ShowDetails>();    \r\n ");
            
            #line 42 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
 if(table.GenerateSelectorControl) { 
            
            #line default
            #line hidden
            this.Write("            services.AddTransient<ctrl");
            
            #line 43 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("SelectorCard>();    \r\n");
            
            #line 44 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    \r\n \r\n");
            
            #line 46 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            return services;\r\n        }\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
