// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templates.UI.DependencyInjection
{
    using System.Linq;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class DependencyInjectionTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write(@"// <auto-generated>
//     تم توليد هذا الكود آلياً بواسطة المحرك. لا تقم بتعديله يدوياً.
// </auto-generated>

using System;
using FluentValidation;
using Microsoft.Extensions.DependencyInjection;

// استدعاء المجلدات المُولدة (Generated Namespaces)
using ");
            
            #line 13 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Interfaces;\r\nusing ");
            
            #line 14 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Services.Generated;\r\nusing ");
            
            #line 15 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Interfaces;\r\nusing ");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Repositories.Generated;\r\nusing ");
            
            #line 17 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Base; \r\nusing ");
            
            #line 18 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Controls;\r\n\r\nnamespace ");
            
            #line 20 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(@".UI.DependencyInjection.Generated
{
    public static partial class DependencyInjectionSetup
    {
        public static IServiceCollection AddGeneratedDependencies(this IServiceCollection services)
        {
            // 1. AUTO-REGISTER ALL FLUENT VALIDATORS
            // مسح الـ Assembly وتسجيل كل كلاسات الـ Validator بضربة واحدة
            services.AddValidatorsFromAssemblyContaining<BaseService>();

            // 2. REGISTER GENERATED REPOSITORIES & SERVICES & UI CONTROLS
");
            
            #line 31 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
 foreach(var table in Tables) { 
            
            #line default
            #line hidden
            this.Write("            // --- ");
            
            #line 32 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.EntityName));
            
            #line default
            #line hidden
            this.Write(" ---\r\n            \r\n            // Business & Data Layers (Scoped)\r\n            s" +
                    "ervices.AddScoped<I");
            
            #line 35 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.EntityName));
            
            #line default
            #line hidden
            this.Write("Repository, ");
            
            #line 35 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.EntityName));
            
            #line default
            #line hidden
            this.Write("Repository>();\r\n            services.AddScoped<I");
            
            #line 36 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.EntityName));
            
            #line default
            #line hidden
            this.Write("Service, ");
            
            #line 36 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.EntityName));
            
            #line default
            #line hidden
            this.Write("Service>();\r\n            \r\n            // UI Layer (Transient - لضمان إنشاء نافذة" +
                    " جديدة كل مرة يتم طلبها)\r\n            services.AddTransient<ctrl");
            
            #line 39 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.EntityName));
            
            #line default
            #line hidden
            this.Write("List>();    \r\n            services.AddTransient<ctrl");
            
            #line 40 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.EntityName));
            
            #line default
            #line hidden
            this.Write("AddEdit>(); \r\n            services.AddTransient<ctrl");
            
            #line 41 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.EntityName));
            
            #line default
            #line hidden
            this.Write("ShowDetails>();    \r\n");
            
            #line 42 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
 if(table.GenerateSelectorControl) { 
            
            #line default
            #line hidden
            this.Write("            services.AddTransient<ctrl");
            
            #line 43 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.EntityName));
            
            #line default
            #line hidden
            this.Write("SelectorCard>();    \r\n");
            
            #line 44 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    \r\n");
            
            #line 45 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\DependencyInjectionTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"            
            // 3. FIRE CUSTOM DEPENDENCIES HOOK (Safe Segregation)
            // السماح للمبرمج بتسجيل خدماته المخصصة في ملف منفصل
            RegisterCustomDependencies(services);

            return services;
        }

        // الخطاف (Hook): إذا لم يكتب المبرمج هذا الكود، سيتم تجاهله وقت الـ Compile (Zero Overhead)
        static partial void RegisterCustomDependencies(IServiceCollection services);
    }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
