// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templates.UI.DependencyInjection
{
    using System.Linq;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class ViewRegistryTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 5 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"

    // =====================================================================
    // NOTE: This assumes you have your schema extraction logic here.
    // For example, fetching a list of 'Table' objects from SQL Server.
    // var Tables = GetDatabaseTables(); 
    // =====================================================================

            
            #line default
            #line hidden
            this.Write(@"// =========================================================================
// AUTO-GENERATED FILE - DO NOT MODIFY MANUALLY
// Any changes made here will be lost when the T4 template is regenerated.
// =========================================================================
namespace CodeGeneratorSolution.UI.Routing
{
    public partial class ViewRegistry
    {
        public ViewRegistry()
        {
            // 1. Load the auto-generated defaults
            RegisterStandardRoutes();

            // 2. Fire the custom hook (if the developer implemented it)
            RegisterCustomRoutes(); 
        }

        private void RegisterStandardRoutes()
        {
");
            
            #line 31 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
 
        // Loop through every table in your database model
        foreach (var table in Tables)
        { 

            
            #line default
            #line hidden
            this.Write("            // --- ");
            
            #line 36 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write(" Routes ---\r\n            RegisterDetails<");
            
            #line 37 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDTO, ctrl");
            
            #line 37 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("ShowDetails>();\r\n            RegisterEditor<");
            
            #line 38 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDTO, ctrl");
            
            #line 38 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.ClassName));
            
            #line default
            #line hidden
            this.Write("AddEdit>();\r\n            \r\n");
            
            #line 40 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
 
        } 

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        // The Extensibility Hook (Notice there is no body!)\r\n      " +
                    "  partial void RegisterCustomRoutes();\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
