// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templates.UI.DependencyInjection
{
    using System.Linq;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class ViewRegistryTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("// <auto-generated>\r\n//     تم توليد هذا الكود آلياً بواسطة المحرك. لا تقم بتعديل" +
                    "ه يدوياً.\r\n// </auto-generated>\r\n\r\nusing ");
            
            #line 8 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs; \r\nusing ");
            
            #line 9 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Controls;\r\n\r\nnamespace ");
            
            #line 11 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(@".UI.Routing
{
    public partial class ViewRegistry
    {
        public ViewRegistry()
        {
            // 1. Load the auto-generated defaults
            RegisterStandardRoutes();

            // 2. Fire the custom hook (if the developer implemented it)
            RegisterCustomRoutes(); 
        }

        private void RegisterStandardRoutes()
        {
");
            
            #line 26 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
 foreach (var table in Tables) { 
            
            #line default
            #line hidden
            this.Write("            // --- ");
            
            #line 27 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.EntityName));
            
            #line default
            #line hidden
            this.Write(" Routes ---\r\n            RegisterDetails<");
            
            #line 28 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.EntityName));
            
            #line default
            #line hidden
            this.Write("ListDTO, ctrl");
            
            #line 28 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.EntityName));
            
            #line default
            #line hidden
            this.Write("ShowDetails>();\r\n            RegisterEditor<");
            
            #line 29 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.EntityName));
            
            #line default
            #line hidden
            this.Write("ListDTO, ctrl");
            
            #line 29 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(table.EntityName));
            
            #line default
            #line hidden
            this.Write("AddEdit>();\r\n            \r\n");
            
            #line 31 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\DependencyInjection\ViewRegistryTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        // The Extensibility Hook (Safe Segregation)\r\n        partia" +
                    "l void RegisterCustomRoutes();\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
