// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templates.Core.Entities
{
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Entities\EntityTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class EntityTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing ");
            
            #line 5 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Entities\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Entities.Base; \r\n\r\nnamespace ");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Entities\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Entities\r\n{\r\n");
            
            #line 9 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Entities\EntityTemplate.tt"
 

    // 3. Construct the Base Class string
    string baseClass = Table.IsAuditable 
        ? $"AuditableEntity<{Table.PkType}, {Table.PrimaryKey.PrimitiveCSharpType}>" 
        : $"Entity<{Table.PkType}>";

            
            #line default
            #line hidden
            this.Write("    public class ");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Entities\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Entities\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(baseClass));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n");
            
            #line 18 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Entities\EntityTemplate.tt"
 
    foreach(var col in Table.Columns) 
    {
        // 1. SKIP Primary Key (Handled by Entity)
        if (col.IsPrimaryKey) continue;

        // 2. SKIP Audit Fields (Handled by AuditableEntity)
        if (col.IsAuditable) 
            continue;

        // 3. GENERATE PROPERTIES

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 30 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Entities\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 30 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Entities\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 31 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Entities\EntityTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write("        // ==========================================\r\n        // OPTIONAL: Navig" +
                    "ation Properties for FKs\r\n        // ==========================================\r" +
                    "\n");
            
            #line 37 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Entities\EntityTemplate.tt"
 /*
    // If CreatedBy is a Foreign Key, you might want the object too
    if (isAuditable && Table.Columns.Any(c => c.Name == "CreatedBy" && c.IsForeignKey))
    {

            
            #line default
            #line hidden
            this.Write("        // Navigation Property (Optional, if you use full ORM or manual Joins)\r\n " +
                    "       // public User CreatorUser { get; set; }\r\n");
            
            #line 44 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Entities\EntityTemplate.tt"
 
    }*/

            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
