// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templates.Core.Mapping
{
    using System.Collections.Generic;
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class MappingExtensionTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\nusing System;\r\nusing ");
            
            #line 6 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Entities;\r\nusing ");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\n\r\nnamespace ");
            
            #line 9 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Mapping\r\n{\r\n    public static partial class ");
            
            #line 11 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("MappingExtensions\r\n    {\r\n        // ==========================================\r\n" +
                    "        // 1. TO DTO (Entity -> DTO)\r\n        // ===============================" +
                    "===========\r\n        public static ");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO ToDto(this ");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity)\r\n        {\r\n            if (entity == null) return null;\r\n\r\n            " +
                    "var dto = new ");
            
            #line 20 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO(){ Id = entity.Id};\r\n\r\n");
            
            #line 22 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
 
    foreach(var col in Table.StandrdDtoColumns) 
    {
       // 2. GENERATE Mapping

            
            #line default
            #line hidden
            this.Write("            dto.");
            
            #line 27 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = entity.");
            
            #line 27 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 28 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write(@"
            // Hook: Custom logic (e.g. formatting dates, computing FullName)
            OnToDto(entity, dto);

            return dto;
        }

        // ==========================================
        // 2. TO ENTITY (DTO -> Entity)
        // ==========================================
        public static ");
            
            #line 41 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" ToEntity(this ");
            
            #line 41 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO dto)\r\n        {\r\n            if (dto == null) return null;\r\n\r\n            var" +
                    " entity = new ");
            
            #line 45 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("();\r\n\r\n               entity.Id = dto.Id;\r\n\r\n");
            
            #line 49 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
 
    foreach(var col in Table.StandrdDtoColumns) 
    {
      

            
            #line default
            #line hidden
            this.Write("            entity.");
            
            #line 54 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = dto.");
            
            #line 54 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 55 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
 
    } 

            
            #line default
            #line hidden
            this.Write(@"
            // Hook: Custom logic (e.g. Hashing Password)
            OnToEntity(dto, entity);

            return entity;
        }

        // ==========================================
        // CREATE: UI -> Entity
        // ==========================================
        public static ");
            
            #line 68 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" ToEntity(this Create");
            
            #line 68 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO dto)\r\n        {\r\n            if (dto == null) return null;\r\n            retur" +
                    "n new ");
            
            #line 71 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("\r\n            {\r\n");
            
            #line 73 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
 foreach(var col in Table.CreateDtoColumns) { 
            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 74 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = dto.");
            
            #line 74 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 75 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            };\r\n        }\r\n\r\n        // =========================================" +
                    "=\r\n        // UPDATE: UI -> Existing Entity\r\n        // ========================" +
                    "==================\r\n        public static void ApplyToEntity(this Update");
            
            #line 82 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO dto, ");
            
            #line 82 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity)\r\n        {\r\n            if (dto == null || entity == null) return;\r\n\r\n  " +
                    "          entity.Id = dto.Id;\r\n            \r\n");
            
            #line 88 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
 foreach(var col in Table.UpdateDtoColumns) { 
            
            #line default
            #line hidden
            this.Write("            entity.");
            
            #line 89 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = dto.");
            
            #line 89 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 90 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write(@"

        }


        // ==========================================
        // 3. PARTIAL METHODS (The Hooks)
        // ==========================================
        // Implement these in a separate file (e.g. UserMappingExtensions.Custom.cs)
        static partial void OnToDto(");
            
            #line 100 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity, ");
            
            #line 100 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO dto);\r\n        static partial void OnToEntity(");
            
            #line 101 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO dto, ");
            
            #line 101 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity);\r\n        static partial void OnToDto(");
            
            #line 102 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity, Create");
            
            #line 102 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO dto);\r\n        static partial void OnToEntity(Create");
            
            #line 103 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO dto, ");
            
            #line 103 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity);\r\n        static partial void OnToDto(");
            
            #line 104 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity, Update");
            
            #line 104 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO dto);\r\n        static partial void OnToEntity(Update");
            
            #line 105 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO dto, ");
            
            #line 105 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Core\Mapping\MappingExtensionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" entity);\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
