// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templates.Application.Services
{
    using System.Linq;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class EntityServiceTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("// <auto-generated>\r\n//     تم توليد هذا الكود آلياً بواسطة المحرك. لا تقم بتعديل" +
                    "ه يدوياً.\r\n// </auto-generated>\r\n\r\nusing System;\r\nusing System.Collections.Gener" +
                    "ic;\r\nusing System.Threading.Tasks;\r\nusing ");
            
            #line 11 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\nusing ");
            
            #line 12 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Mapping;\r\nusing ");
            
            #line 13 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Enums;\r\nusing ");
            
            #line 14 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Entities;\r\nusing ");
            
            #line 15 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Entities.Interfaces; \r\nusing ");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Interfaces; \r\nusing ");
            
            #line 17 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Interfaces;\r\nusing ");
            
            #line 18 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Base;\r\nusing ");
            
            #line 19 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure; \r\nusing ");
            
            #line 20 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Utilities; \r\nusing ");
            
            #line 21 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Interfaces;\r\n\r\nnamespace ");
            
            #line 23 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Services\r\n{\r\n    public partial class ");
            
            #line 25 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("Service : BaseService, I");
            
            #line 25 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("Service\r\n    {\r\n        private readonly I");
            
            #line 27 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("Repository _repository;\r\n\r\n        // حقن كل من ServiceProvider للـ Validation و " +
                    "IUserSession للـ Auditing\r\n        public ");
            
            #line 30 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("Service(\r\n            I");
            
            #line 31 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(@"Repository repository, 
            IServiceProvider serviceProvider, 
            IUserSession session) : base(serviceProvider, session)
        {
            _repository = repository;
        }

        // =========================================================
        // WRITE COMMANDS (Insert, Update, Delete)
        // =========================================================

        public async Task<Result<");
            
            #line 42 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(">> AddAsync(Create");
            
            #line 42 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("DTO dto)\r\n        {\r\n            return await ServiceExecutor.RunAsync<");
            
            #line 44 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(">(async () =>\r\n            {\r\n                // 1. FluentValidation Execution\r\n " +
                    "               var validationResult = await ValidateDtoAsync(dto);\r\n            " +
                    "    if (!validationResult.IsSuccess)\r\n                {\r\n                    ret" +
                    "urn Result<");
            
            #line 50 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(@">.Failure(validationResult.ErrorMessage, ErrorType.Validation);
                }

                // 2. Mapping DTO -> Entity
                var entity = dto.ToEntity();

                // 3. Implicit Auditing (تتبع المستخدم الذي قام بالإضافة)
                if (entity is IAuditableEntity<");
            
            #line 57 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(@", int> auditableEntity)
                {
                    auditableEntity.CreatedBy = _session.UserId;
                    auditableEntity.CreatedDate = DateTime.UtcNow; 
                }

                // 4. Database Operation (Dapper Repository)
                ");
            
            #line 64 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(" newId = await _repository.AddAsync(entity);\r\n\r\n                return Result<");
            
            #line 66 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(">.Success(newId);\r\n            });\r\n        }\r\n\r\n        public async Task<Result" +
                    "<bool>> UpdateAsync(Update");
            
            #line 70 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(@"DTO dto)
        {
            return await ServiceExecutor.RunAsync<bool>(async () =>
            {
                // 1. FluentValidation
                var validationResult = await ValidateDtoAsync(dto);
                if (!validationResult.IsSuccess)
                {
                    return Result<bool>.Failure(validationResult.ErrorMessage, ErrorType.Validation);
                }

                // ملاحظة هندسية: مع Dapper، يجب أن نجلب السجل القديم أولاً لنضمن عدم ضياع بيانات Auditing القديمة كـ CreatedDate
                var existingEntity = await _repository.GetByIdAsync(dto.Id);
                if (existingEntity == null)
                    return Result<bool>.Failure(""");
            
            #line 84 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(@" not found."", ErrorType.NotFound);

                // 2. Apply updates from DTO to the existing Entity
                dto.ApplyToEntity(existingEntity);

                // 3. Implicit Auditing for Update
                if (existingEntity is IAuditableEntity<");
            
            #line 90 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(@", int> auditableEntity)
                {
                    auditableEntity.ModifiedBy = _session.UserId;
                    auditableEntity.ModifiedDate = DateTime.UtcNow;
                }

                // 4. Database Operation
                bool success = await _repository.UpdateAsync(existingEntity);

                return Result<bool>.Success(success);
            });
        }

        public async Task<Result<bool>> DeleteAsync(");
            
            #line 103 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(@" id)
        {
            return await ServiceExecutor.RunActionAsync(async () =>
            {
                await _repository.DeleteAsync(id);
            });
        }

        // =========================================================
        // READ QUERIES (GetList, GetDetails, etc.)
        // =========================================================

        public async Task<Result<IEnumerable<");
            
            #line 115 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("DTO>>> GetAllAsync()\r\n        {\r\n            return await ServiceExecutor.RunAsyn" +
                    "c(async () =>\r\n            {\r\n                var data = await _repository.GetAl" +
                    "lAsync();\r\n                return Result<IEnumerable<");
            
            #line 120 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("DTO>>.Success((IEnumerable<");
            
            #line 120 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("DTO>)data);\r\n            });\r\n        }\r\n\r\n        // تحديث هام: تم إضافة معاملات" +
                    " اللغة والتقسيم (Pagination) ليتوافق مع الـ Repo الجديد\r\n        public async Ta" +
                    "sk<Result<IReadOnlyList<");
            
            #line 125 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("ListDTO>>> GetListAsync(string langCode, int pageNumber = 1, int pageSize = 10)\r\n" +
                    "        {\r\n            return await ServiceExecutor.RunAsync<IReadOnlyList<");
            
            #line 127 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("ListDTO>>(async () =>\r\n            {\r\n                var data = await _repositor" +
                    "y.GetListAsync(langCode, pageNumber, pageSize);\r\n                return Result<I" +
                    "ReadOnlyList<");
            
            #line 130 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("ListDTO>>.Success(data);\r\n            });\r\n        }\r\n\r\n        public async Task" +
                    "<Result<");
            
            #line 134 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("DTO>> GetByIdAsync(");
            
            #line 134 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n            return await ServiceExecutor.RunAsync<");
            
            #line 136 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("DTO>(async () =>\r\n            {\r\n                var data = await _repository.Get" +
                    "ByIdAsync(id);\r\n                \r\n                if (data == null)\r\n           " +
                    "         return Result<");
            
            #line 141 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("DTO>.Failure(\"");
            
            #line 141 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(" not found.\", ErrorType.NotFound);\r\n\r\n                return Result<");
            
            #line 143 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("DTO>.Success(data.ToDto());\r\n            });\r\n        }\r\n\r\n        // تحديث هام: " +
                    "توليد دوال GetDetails و Exists بناءً على المفاتيح المميزة (Unique Selectors)\r\n");
            
            #line 148 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
 foreach(var col in Table.Columns.Where(c => c.IsUniqueSelector)) { 
            
            #line default
            #line hidden
            this.Write("        public async Task<Result<");
            
            #line 149 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO>> GetDetailsAsync(");
            
            #line 149 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 149 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CamelCaseName));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return await ServiceExecutor.RunAsync<");
            
            #line 151 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO>(async () =>\r\n            {\r\n                var data = await _reposit" +
                    "ory.GetDetailsAsync(");
            
            #line 153 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CamelCaseName));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n                if (data == null)\r\n                    return Result<");
            
            #line 156 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO>.Failure(\"");
            
            #line 156 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(" details not found.\", ErrorType.NotFound);\r\n\r\n                return Result<");
            
            #line 158 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO>.Success(data);\r\n            });\r\n        }\r\n\r\n        public async Ta" +
                    "sk<Result<bool>> ExistsAsync(");
            
            #line 162 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 162 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CamelCaseName));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n            return await ServiceExecutor.RunAsync<bool>(async () =>" +
                    "\r\n            {\r\n                bool exists = await _repository.ExistsAsync(");
            
            #line 166 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CamelCaseName));
            
            #line default
            #line hidden
            this.Write(");\r\n                return Result<bool>.Success(exists);\r\n            });\r\n      " +
                    "  }\r\n");
            
            #line 170 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
