// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templates.Application.Services
{
    using System.Linq;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class EntityServiceTemplate : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Linq;\r\nusing Syste" +
                    "m.Threading.Tasks;\r\nusing FluentValidation;\r\nusing ");
            
            #line 9 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\nusing ");
            
            #line 10 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Mapping;\r\nusing ");
            
            #line 11 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Enums;\r\nusing ");
            
            #line 12 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Entities;\r\nusing ");
            
            #line 13 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Interfaces;\r\nusing ");
            
            #line 14 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Interfaces;\r\nusing ");
            
            #line 15 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure; // For ServiceExecutor\r\nusing ");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Utilities; // For Result<T>\r\nusing ");
            
            #line 17 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Infrastructure.Repositories;\r\nusing ");
            
            #line 18 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Base;\r\n\r\n\r\nnamespace ");
            
            #line 21 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Services\r\n{\r\n\r\n   public class ");
            
            #line 24 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service : BaseService\r\n    ,I");
            
            #line 25 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service\r\n    {\r\n        private readonly I");
            
            #line 27 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Repository _repository;\r\n\r\n        // Dependency Injection now demands the Repo a" +
                    "nd the global Waiter (ServiceProvider)\r\n        public ");
            
            #line 30 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service(I");
            
            #line 30 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Repository repository,IServiceProvider serviceProvider) : base(serviceProvider)\r\n" +
                    "        {\r\n            _repository = repository;\r\n        }\r\n\r\n        public as" +
                    "ync Task<Result<IEnumerable<");
            
            #line 35 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO>>> GetAllAsync()\r\n        {\r\n            return await ServiceExecutor.RunAsyn" +
                    "c(async () =>\r\n            {\r\n                var data = await _repository.GetAl" +
                    "lAsync();\r\n                return Result<IEnumerable<");
            
            #line 40 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO>>.Success((IEnumerable<");
            
            #line 40 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO>)data);\r\n            });\r\n        }\r\n\r\n        public async Task<Result<IRead" +
                    "OnlyList<");
            
            #line 44 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDTO>>> GetListAsync()\r\n        {\r\n            return await ServiceExecutor.Ru" +
                    "nAsync<IReadOnlyList<");
            
            #line 46 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDTO>>(async () =>\r\n            {\r\n                var data = await _repositor" +
                    "y.GetListAsync();\r\n                return Result<IReadOnlyList<");
            
            #line 49 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ListDTO>>.Success(data);\r\n            });\r\n        }\r\n\r\n        public async Task" +
                    "<Result<");
            
            #line 53 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO>> GetByIdAsync( ");
            
            #line 53 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n            return await ServiceExecutor.RunAsync<");
            
            #line 55 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO>(async () =>\r\n            {\r\n                var data = await _repository.Get" +
                    "ByIdAsync(id);\r\n                \r\n                if (data == null)\r\n           " +
                    "         return Result<");
            
            #line 60 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO>.Failure(\"");
            
            #line 60 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(" not found.\", ErrorType.NotFound);\r\n\r\n                return Result<");
            
            #line 62 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO>.Success(data.ToDto());\r\n            });\r\n        }\r\n\r\n        public async T" +
                    "ask<Result<");
            
            #line 66 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO>> GetDetailsAsync(");
            
            #line 66 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n            return await ServiceExecutor.RunAsync<");
            
            #line 68 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO>(async () =>\r\n            {\r\n                // 1. Call the pure Read-" +
                    "Only Repository method. \r\n                // This returns a ");
            
            #line 71 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO directly, NOT a Student Entity.\r\n                var data = await _rep" +
                    "ository.GetDetailsAsync(id);\r\n\r\n                if (data == null)\r\n             " +
                    "       return Result<");
            
            #line 75 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO>.Failure(\"Student not found.\", ErrorType.NotFound);\r\n\r\n               " +
                    " // 2. Since \'data\' is ALREADY a ");
            
            #line 77 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO, we just pass it! No .ToDto() needed!\r\n                return Result<");
            
            #line 78 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO>.Success(data);\r\n            });\r\n        }\r\n        public async Task" +
                    "<Result<");
            
            #line 81 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(">> AddAsync(Create");
            
            #line 81 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DTO dto)\r\n        {\r\n            return await ServiceExecutor.RunAsync<");
            
            #line 83 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(@">(async () =>
            {
                // --- 1. FluentValidation Execution using the BaseService Helper ---
                var validationResult = await ValidateDtoAsync(dto);
                
                if (!validationResult.IsSuccess)
                {
                    // Fails gracefully returning the FluentValidation error string
                    return Result<");
            
            #line 91 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(">.Failure(validationResult.ErrorMessage,ErrorType.Validation);\r\n                }" +
                    "\r\n\r\n                // --- 2. Database Operation ---\r\n                 ");
            
            #line 95 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(" NewId;\r\n\r\n                NewId = await _repository.AddAsync(dto.ToEntity()); //" +
                    " Ensure your AddAsync returns ");
            
            #line 97 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write("/TKey\r\n\r\n                return Result<");
            
            #line 99 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(">.Success(NewId);\r\n            });\r\n        }\r\n\r\n        public async Task<Result" +
                    "<bool>> UpdateAsync(Update");
            
            #line 103 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"DTO dto)
        {
            return await ServiceExecutor.RunAsync<bool>(async () =>
            {
                // --- 1. FluentValidation Execution using the BaseService Helper ---
                var validationResult = await ValidateDtoAsync(dto);
                
                if (!validationResult.IsSuccess)
                {
                    // Fails gracefully returning the FluentValidation error string
                    return Result<bool>.Failure(validationResult.ErrorMessage, ErrorType.Validation);
                }

                // --- 2. Database Operation ---
                bool success;
                var entity = new ");
            
            #line 118 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"();
                dto.ApplyToEntity(entity);

                success = await _repository.UpdateAsync(entity);

                return Result<bool>.Success(success);
            });
        }

        public async Task<Result<bool>> DeleteAsync(");
            
            #line 127 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(" id)\r\n        {\r\n            return await ServiceExecutor.RunActionAsync(async ()" +
                    " =>\r\n            {\r\n                await _repository.DeleteAsync(id);\r\n        " +
                    "    });\r\n        }\r\n\r\n         public async Task<Result<bool>> ExistsAsync(");
            
            #line 135 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\Application\Services\EntityServiceTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(@" id)
        {
            return await ServiceExecutor.RunAsync<bool>(async () =>
            {
                var data = await _repository.ExistsAsync(id);
                
                if (data == null)
                    return Result<bool>.Failure(""Student not found."",ErrorType.NotFound);

                return Result<bool>.Success(data);
            });
        }
    }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
