// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templates.UI.Controls
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class ctrlShowDetails : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 5 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
 
    var displayColumns = Table.DetailedColumns;
    
    // حساب أقصى عدد للأعمدة بناءً على الميتاداتا
    int maxColumns = displayColumns.Any(c => c.UIColumn.HasValue) 
        ? displayColumns.Max(c => (c.UIColumn ?? 0) + (c.UIColSpan ?? 1)) 
        : 1;

            
            #line default
            #line hidden
            this.Write(@"// <auto-generated>
//     تم توليد هذا الكود آلياً. لا تقم بتعديله يدوياً.
//     استخدم ملف الكلاس الجزئي (Partial Class) لإضافة الأكواد المخصصة.
// </auto-generated>

using System;
using System.Threading.Tasks;
using System.Windows.Forms;
using ModernUI.Framework.Controls;
using ");
            
            #line 22 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\nusing ");
            
            #line 23 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs.Interfaces;\r\nusing ");
            
            #line 24 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Interfaces;\r\nusing ");
            
            #line 25 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Helpers; \r\nusing ");
            
            #line 26 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Interfaces;\r\nusing ");
            
            #line 27 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Controls;\r\nusing ");
            
            #line 28 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.Context; \r\n\r\nnamespace ");
            
            #line 30 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Controls\r\n{\r\n    [System.ComponentModel.ToolboxItem(false)]\r\n    public parti" +
                    "al class ctrl");
            
            #line 33 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(@"ShowDetails : ShowDetailsBaseControl, IDetailsControl
    {
        // ====================================================
        // 1. DYNAMIC UI FIELDS (Strongly Typed for IntelliSense)
        // ====================================================
");
            
            #line 38 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
 foreach(var col in displayColumns) { 
     if (col.MetaIsPassword == true) continue; 
            
            #line default
            #line hidden
            this.Write("        public ModernDisplayField mdf");
            
            #line 40 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" { get; private set; }\r\n");
            
            #line 41 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        // ====================================================\r\n        // 2. " +
                    "DEPENDENCIES & INTERFACE IMPLEMENTATION\r\n        // ============================" +
                    "========================\r\n        private readonly I");
            
            #line 46 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("Service _service;\r\n        private ");
            
            #line 47 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(@" _currentId;

        public UserControl AsUserControl() => this; 
        public event EventHandler DataLoaded;
        
        // دعم لغتين لعنوان النافذة (Tab أو Popup)
        public string Title => AppLayoutContext.IsArabicLayout 
            ? ""تفاصيل ");
            
            #line 54 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.FriendlyNameAr));
            
            #line default
            #line hidden
            this.Write("\" \r\n            : \"");
            
            #line 55 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.FriendlyNameEn));
            
            #line default
            #line hidden
            this.Write(" Details\";\r\n\r\n        // ====================================================\r\n  " +
                    "      // 3. CONSTRUCTOR & HEADER LOGIC\r\n        // =============================" +
                    "=======================\r\n        public ctrl");
            
            #line 60 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("ShowDetails(I");
            
            #line 60 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(@"Service service)
        {
            InitializeComponent();
            _service = service;
            
            bool isHandled = false;
            OnConfigureHeader(_mainHeader,ref isHandled);
            UpdateHeaderUI(isHandled);
        }

     // ====================================================
        // تحديث الـ ModernControlHeader ببيانات الجدول
        // ====================================================
        private void UpdateHeaderUI(bool isHandled)
        {
            if (isHandled || _mainHeader == null) return;

            // تحديد العنوان ديناميكياً بدعم اللغتين
            _mainHeader.Title = AppLayoutContext.IsArabicLayout 
                ? """);
            
            #line 79 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.FriendlyNameAr));
            
            #line default
            #line hidden
            this.Write(" تفاصيل\" \r\n                : \"");
            
            #line 80 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(" Details\";\r\n\r\n\r\n\r\n                // مثال: _mainHeader.Title = this.Title;\r\n     " +
                    "       //ResourceImageHelper.ApplyEntityIcon(_mainHeader.HeaderImage, \"");
            
            #line 85 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(@""", ""view"");

            // تحديد أيقونة تناسب اسم الجدول (يمكنك جلبها من Metadata الجدول)
            // افتراض أن لديك دالة تجلب كود الأيقونة المناسب للجدول
           // _mainHeader.IconText = ModernUI.Framework.Icons.SegoeIcons.Document.Solid; 
            
            // يمكن ربط اللون بـ ThemeManager الخاص بك
           // _mainHeader.IconColor = System.Drawing.Color.FromArgb(52, 152, 219); 
        }

        // خطاف (Hook) ممرر إليه كائن الـ Header القوي الخاص بك
        partial void OnConfigureHeader(ModernControlHeader header, ref bool isHandled);
        partial void OnDataLoaded(");
            
            #line 97 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(@"DetailsDTO dto);

        // ====================================================
        // 4. LOAD DATA (From Database)
        // ====================================================
        public async Task LoadDataAsync(object id)
        {
            // استخدام ChangeType للحماية من مشاكل الـ Unboxing
            _currentId = (");
            
            #line 105 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(")Convert.ChangeType(id, typeof(");
            
            #line 105 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(@"));
            
            var result = await _service.GetByIdAsync(_currentId);

            if (result != null && result.IsSuccess && result.Value != null)
            {
                FillControl(result.Value);
            }
            else
            {
                // إظهار رسالة خطأ فقط إذا فشل الجلب
                MessageServiceHelper.PopupMessage(result);
            }
        }

        // ====================================================
        // 5. DTO TO UI MAPPING (Grid Layout)
        // ====================================================
        public void FillControl(IDto dto)
        {
            var ");
            
            #line 125 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.CamelCaseName));
            
            #line default
            #line hidden
            this.Write(" = dto as ");
            
            #line 125 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO;\r\n            if (");
            
            #line 126 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.CamelCaseName));
            
            #line default
            #line hidden
            this.Write(" == null) return;\r\n\r\n            // إيقاف الرسم وتجهيز شبكة عرض البيانات\r\n       " +
                    "     BeginDataUpdate(");
            
            #line 129 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(maxColumns));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n");
            
            #line 131 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
 
            int autoRowIndex = 0;
            foreach(var col in displayColumns) { 
                if (col.MetaIsPassword == true) continue; 
                
                string icon = col.IconOutline.Replace("\"", "\\\"");
                string labelAr = col.FriendlyNameAr.Replace("\"", "\\\"");
                string labelEn = col.FriendlyNameEn.Replace("\"", "\\\"");
                
                int uiRow = col.UIRow ?? autoRowIndex++;
                int uiCol = col.UIColumn ?? 0;
                int uiColSpan = col.UIColSpan ?? 1;

                // Value Formatting Logic
                string valueFormat = "";
                if (col.CSharpType == "bool") {
                    valueFormat = $"{Table.CamelCaseName}.{col.Name} ? (AppLayoutContext.IsArabicLayout ? \"نعم\" : \"Yes\") : (AppLayoutContext.IsArabicLayout ? \"لا\" : \"No\")";
                } 
                else if (col.CSharpType == "DateTime" || col.CSharpType == "DateTime?") {
                    valueFormat = $"{Table.CamelCaseName}.{col.Name}?.ToLocalTime().ToString(\"dd/MM/yyyy\")";
                }
                else if (col.CSharpType == "decimal" || col.CSharpType == "double" || col.CSharpType == "decimal?" || col.CSharpType == "double?") {
                    valueFormat = $"{Table.CamelCaseName}.{col.Name}?.ToString(\"C2\")";
                }
                else {
                    valueFormat = $"{Table.CamelCaseName}.{col.Name}?.ToString()";
                }

            
            #line default
            #line hidden
            this.Write("            mdf");
            
            #line 159 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(" = AddDetailField(\r\n                iconCode: \"");
            
            #line 160 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(icon));
            
            #line default
            #line hidden
            this.Write("\", \r\n                displayName: AppLayoutContext.IsArabicLayout ? \"");
            
            #line 161 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(labelAr));
            
            #line default
            #line hidden
            this.Write("\" : \"");
            
            #line 161 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(labelEn));
            
            #line default
            #line hidden
            this.Write("\", \r\n                stringValue: ");
            
            #line 162 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(valueFormat));
            
            #line default
            #line hidden
            this.Write(", \r\n                uiRow: ");
            
            #line 163 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(uiRow));
            
            #line default
            #line hidden
            this.Write(", \r\n                uiColumn: ");
            
            #line 164 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(uiCol));
            
            #line default
            #line hidden
            this.Write(", \r\n                uiColSpan: ");
            
            #line 165 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(uiColSpan));
            
            #line default
            #line hidden
            this.Write("\r\n            );\r\n");
            
            #line 167 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n            EndDataUpdate();\r\n            \r\n            // استدعاء الخطاف ليتيح" +
                    " للمبرمج تغيير ألوان الحقول بعد تحميل البيانات\r\n            OnDataLoaded(");
            
            #line 172 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetails.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.CamelCaseName));
            
            #line default
            #line hidden
            this.Write(");\r\n        }\r\n    }\r\n    \r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
