// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templates.UI.Controls
{
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class ctrlSelectorCard : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 3 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
 
    var uniqueSelectors = Table.Columns.Where(c => c.IsUniqueSelector);

            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Threading.Tasks;\r\n" +
                    "using System.Windows.Forms;\r\nusing ");
            
            #line 10 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Core.DTOs;\r\nusing ");
            
            #line 11 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application.Interfaces;\r\nusing ");
            
            #line 12 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Helpers; \r\nusing ");
            
            #line 13 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Interfaces;\r\nusing ");
            
            #line 14 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".Application; // For Result<T>\r\n\r\nnamespace ");
            
            #line 16 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Controls\r\n{\r\n    public partial class ctrl");
            
            #line 18 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("SelectorCard : UserControl, ISelectorControl<");
            
            #line 18 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        // ====================================================\r\n      " +
                    "  // 1. DYNAMIC FILTERING & STRATEGY PATTERN\r\n        // =======================" +
                    "=============================\r\n        public enum FindBy \r\n        { \r\n");
            
            #line 25 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
 foreach(var col in uniqueSelectors) { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 26 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(", \r\n");
            
            #line 27 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public readonly List<KeyValuePair<FindBy, string>> FilterDis" +
                    "playNames = new List<KeyValuePair<FindBy, string>>\r\n        {\r\n");
            
            #line 32 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
 foreach(var col in uniqueSelectors) { 
            
            #line default
            #line hidden
            this.Write("            new KeyValuePair<FindBy, string>(FindBy.");
            
            #line 33 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(", \"");
            
            #line 33 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.FriendlyName));
            
            #line default
            #line hidden
            this.Write("\"),\r\n");
            
            #line 34 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        };\r\n\r\n        private readonly Dictionary<FindBy, Func<string, Task<Resul" +
                    "t<");
            
            #line 37 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO>>>> _searchStrategies;\r\n\r\n        private readonly I");
            
            #line 39 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service _service;\r\n        private readonly ctrl");
            
            #line 40 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("ShowDetails _detailsCtrl;\r\n        private  ");
            
            #line 41 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkType));
            
            #line default
            #line hidden
            this.Write("  _currentId;\r\n\r\n        public event EventHandler<IIdentifiableDto> OnItemSelected;\r\n\r\n " +
                    "       public ctrl");
            
            #line 45 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("SelectorCard(I");
            
            #line 45 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("Service service, ctrl");
            
            #line 45 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"ShowDetails detailsCtrl)
        {
            InitializeComponent();
            _service = service;
            _detailsCtrl = detailsCtrl;
            
            _detailsCtrl.Dock = DockStyle.Fill;
            this.pnlDetailsContainer.Controls.Add(_detailsCtrl);
           
            
            cbFindBy.DataSource = new BindingSource(FilterDisplayNames, null);
            cbFindBy.DisplayMember = ""Value"";
            cbFindBy.ValueMember = ""Key"";

            // 1. Initialize Default Strategies
            _searchStrategies = InitializeSearchStrategies();
            
            // 2. NEW HOOK: Allow developer to add/override strategies dynamically
            OnRegisterCustomSearchStrategies(_searchStrategies);
        }

        // ====================================================
        // 2. STRATEGY INITIALIZATION
        // ====================================================
        private Dictionary<FindBy, Func<string, Task<Result<");
            
            #line 69 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO>>>> InitializeSearchStrategies()\r\n        {\r\n            return new Di" +
                    "ctionary<FindBy, Func<string, Task<Result<");
            
            #line 71 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO>>>>\r\n            {\r\n");
            
            #line 73 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
 foreach(var col in uniqueSelectors) { 
    if (col.CSharpType == "string") { 
            
            #line default
            #line hidden
            this.Write("                { FindBy.");
            
            #line 75 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(", async (text) => await _service.GetDetailsBy");
            
            #line 75 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Async(text) },\r\n");
            
            #line 76 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
  } else { 
            
            #line default
            #line hidden
            this.Write("                { FindBy.");
            
            #line 77 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write(", async (text) => \r\n                    {\r\n                        if (!");
            
            #line 79 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.CSharpType));
            
            #line default
            #line hidden
            this.Write(".TryParse(text, out var parsedValue))\r\n                            return Result<" +
                    "");
            
            #line 80 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO>.Failure(\"Invalid format for ");
            
            #line 80 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.FriendlyName));
            
            #line default
            #line hidden
            this.Write(".\");\r\n                            \r\n                        return await _service" +
                    ".GetDetailsBy");
            
            #line 82 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(col.Name));
            
            #line default
            #line hidden
            this.Write("Async(parsedValue);\r\n                    } \r\n                },\r\n");
            
            #line 85 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
  }
} 
            
            #line default
            #line hidden
            this.Write("            };\r\n        }\r\n\r\n        partial void OnRegisterCustomSearchStrategie" +
                    "s(Dictionary<FindBy, Func<string, Task<Result<");
            
            #line 90 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"DetailsDTO>>>> strategies);

        // ====================================================
        // 3. THE DECOUPLED SEARCH EXECUTION (Guard Clauses Applied)
        // ====================================================
        private async void btnSearch_Click(object sender, EventArgs e)
        {
            string searchText = txtSearch.Text.Trim();
            
            // Guards
            if (string.IsNullOrEmpty(searchText)) return;
            if (cbFindBy.SelectedValue == null) return;
            if (!(cbFindBy.SelectedValue is FindBy selectedFilter)) return;

            ");
            
            #line 104 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"DetailsDTO resulTReadDTO = null;
            bool isCustomSearchHandled = false;

            // HOOK: Allow complete bypass
            OnCustomSearch(selectedFilter, searchText, ref resulTReadDTO, ref isCustomSearchHandled);

            if (isCustomSearchHandled)
            {
                ProcessSearchResult(resulTReadDTO);
                return; // Guard: Custom search finished it.
            }

            resulTReadDTO = await ExecuteSearchAsync(selectedFilter, searchText);
            ProcessSearchResult(resulTReadDTO);
        }

        private async Task<");
            
            #line 120 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"DetailsDTO> ExecuteSearchAsync(FindBy filter, string text)
        {
            // Guard: Strategy missing
            if (!_searchStrategies.TryGetValue(filter, out var searchFunction)) return null; 

            try
            {
                var result = await searchFunction(text);
                
                // Guard: Null safety
                if (result == null) return null; 

                // Guard: Success Path
                if (result.IsSuccess) return result.Data;

                // Expected BLL Failures (Validation, NotFound) handled gracefully by your central UI helper!
                MessageServiceHelper.PopupMessage(result);
                return null;
            }
            catch (Exception ex)
            {
                // Catastrophic Infrastructure Failures (DB Offline, Out of Memory)
                MessageServiceHelper.ShowError($""An unexpected infrastructure error occurred: {ex.Message}"", ""System Error"");
                return null;
            }
        }

        private void ProcessSearchResult(");
            
            #line 147 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write(@"DetailsDTO resulTReadDTO)
        {
            // Guard: Search failed, clear UI
            if (resulTReadDTO == null)
            {
                _detailsCtrl.LoadData(null); 
                return; 
            }

            // Success Path
            _currentId = resulTReadDTO.");
            
            #line 157 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.PkName));
            
            #line default
            #line hidden
            this.Write(";\r\n            _detailsCtrl.LoadData(resulTReadDTO);\r\n            OnItemSelected?.Inv" +
                    "oke(this, (IIdentifiableDto)resulTReadDTO);\r\n        }\r\n\r\n        partial void OnCustomSearc" +
                    "h(FindBy filterType, string searchText, ref ");
            
            #line 162 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlSelectorCard.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.ClassName));
            
            #line default
            #line hidden
            this.Write("DetailsDTO resulTReadDTO, ref bool isHandled);\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
