// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 18.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGeneratorSolution.Templates.UI.Controls
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetailsControlDesigner.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "18.0.0.0")]
    public partial class ctrlShowDetailsControlDesigner : CodeGeneratorSolution.Models.TemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("// <auto-generated>\r\n//     تم توليد هذا الكود آلياً.\r\n//     أي تعديل يدوي في هذ" +
                    "ا الملف سيتم فقدانه عند إعادة التوليد.\r\n// </auto-generated>\r\n\r\nnamespace ");
            
            #line 7 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetailsControlDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(SolutionName));
            
            #line default
            #line hidden
            this.Write(".UI.Controls\r\n{\r\n    partial class ctrl");
            
            #line 9 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetailsControlDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write(@"ShowDetails
    {
        /// <summary> 
        /// متغير ضروري لمصمم الواجهات (Designer).
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// تنظيف الموارد (Resources) المستخدمة.
        /// </summary>
        /// <param name=""disposing"">true إذا كان يجب التخلص من الموارد المدارة؛ خلاف ذلك false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// الطريقة المطلوبة لدعم المصمم (Designer).
        /// لا تقم بتعديل محتوى هذه الطريقة باستخدام محرر الأكواد.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            
            // تهيئة إعدادات الكنترول الأساسية
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Name = ""ctrl");
            
            #line 41 "C:\Users\OsamaEhab\source\repos\CodeGeneratorSolution\Templates\UI\Controls\ctrlShowDetailsControlDesigner.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Table.EntityName));
            
            #line default
            #line hidden
            this.Write("ShowDetails\";\r\n            \r\n            // يمكنك تعيين حجم افتراضي مناسب للكنترو" +
                    "ل\r\n            this.Size = new System.Drawing.Size(800, 600);\r\n        }\r\n\r\n    " +
                    "    #endregion\r\n    }\r\n}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
